// Songs data for The Zikaron Project
// Refactored to interleave Hebrew, Transliteration, and English lines.

const songs = [
  {
    id: 1,
    title: "We'll Meet in Dreams",
    titleHebrew: "ניפגש בחלומות",
    artist: "Ilai Botner and Yaldei Hachutz",
    videoUrl: "4J7bQpp_MGo",
    credits: "Written by Noam Chorev, Composed by Ilai Botner, Performed by Ilai Botner and Yaldei Hachutz, Translated (and adapted) by Naama Ben-Dor.",
    context: "This video is part of my project to share English translations of Hebrew remembrance songs with the global community, in an effort to connect Jews throughout the diaspora in their shared pain and experiences.",
    lyrics: [
      { he: "עוד נחזור להיפגש, להסתכל שוב בעיניים.", tr: "Od nachzor lehipagesh, lehistakel shuv ba'einayim.", en: "And we'll meet once again, gaze into each other's eyes." },
      { he: "יש פקק תפילות כבד בנתיב של השמיים.", tr: "Yesh pkak tfilot kaved b'nativ shel hashamayim.", en: "There's a traffic jam of prayers—on the road to the skies." },
      { he: "אבל החוט הדק בינינו אף פעם לא נקרע.", tr: "Aval hachut hadak beineinu af pa'am lo nikra.", en: "But the thin thread connecting us will never tear apart." },
      { he: "עוד נצחק שם על הכל, לא תהיה לנו ברירה.", tr: "Od nitzchak sham al hakol, lo tihyeh lanu breira.", en: "We'll laugh about it all someday, it's the only choice we have." },
      { he: "", tr: "", en: "" },
      { he: "עוד נצא שוב לטייל בבוקר של שבת,", tr: "Od netze shuv letayel baboker shel shabbat,", en: "And once again we'll go outside, go for walks on Shabbat mornings," },
      { he: "נחזיר את השיגרה האבודה לאט לאט.", tr: "Nachzir et hashigra ha'avuda le'at le'at.", en: "Restore the old routine that we've lost—slowly, slowly." },
      { he: "נקום מהספה, ננשום את האוויר.", tr: "Nakum mehasapa, ninshom et ha'avir.", en: "We'll get up off the couch, and breathe in the air." },
      { he: "למדנו עם הזמן שהכל כל כך שביר.", tr: "Lamadnu im hazman shehakol kol kach shavir.", en: "We've learned, with time, how easily—everything can break." },
      { he: "", tr: "", en: "" },
      { he: "ובינתיים ניפגש בחלומות—", tr: "Uveintayim nipagesh bachalomot—", en: "And for now, we will meet in our dreams—" },
      { he: "אני איתך בכל שעה, בכל הנשימות;", tr: "Ani itcha bechol sha'a, bechol haneshimot;", en: "I'm with you in every hour, in the air you breathe;" },
      { he: "ואם אתה עמוק מתחת לשמיכה;", tr: "Ve'im ata amok mitachat lasmicha;", en: "And if you're underneath the covers, off to sleep;" },
      { he: "תשאיר לי את הדלת חצי פתוחה.", tr: "Tash'ir li et hadelet chatzi ptucha.", en: "Leave the door half-open; just for me." },
      { he: "", tr: "", en: "" },
      { he: "אני שולחת ידיים ארוכות;", tr: "Ani sholachat yadayim arukot;", en: "I am sending myself forth with open arms;" },
      { he: "הן מחבקות אותך עכשיו, הן מחבקות.", tr: "Hen mechabkot otcha achshav, hen mechabkot.", en: "They're wrapped around you now—they hug and guard." },
      { he: "ורק תזכור, שניה, לפני שאתה נרדם,", tr: "Verak tizkor, shniya, lifnei she'ata nirdam,", en: "And just before you fall asleep, lying curled," },
      { he: "שגעגוע הוא הדבק הכי חזק בעולם.", tr: "Shega'agu'a hu hadevek hachi chazak ba'olam.", en: "Remember longing is the strongest glue in the world." },
      { he: "", tr: "", en: "" },
      { he: "עוד נחזור שוב לשחק, להתפרק בחיבוק,", tr: "Od nachzor shuv lesachek, lehitparek bechibuk,", en: "One day we'll play again, and part with an embrace," },
      { he: "השניה הכי קשה היא אחרי הניתוק,", tr: "Hashniya hachi kasha hi acharei hanituk,", en: "And wince in pain the moment we are split apart by space," },
      { he: "ושער הדמעות שלי נפתח שוב לרווחה,", tr: "Vesha'ar hadma'ot sheli niftach shuv lirvacha,", en: "The floodgates of my tears open quickly, vast and wide," },
      { he: "כי יש עוגה, ויש נרות, אבל אין לי כאן אותך;", tr: "Ki yesh uga, veyesh nerot, aval ein li kan otcha;", en: "'Cause there's cake, and there are candles, but you're not here by my side;" },
      { he: "", tr: "", en: "" },
      { he: "עוד נחזור להיפגש, נשכב סתם על הגב,", tr: "Od nachzor lehipagesh, nishkav stam al hagav,", en: "We'll meet again someday, lie casually on our backs," },
      { he: "לא ניקח שום דבר כמובן מאליו.", tr: "Lo nikach shum davar kamuvan me'alav.", en: "And never take for granted anything we'll ever have." },
      { he: "וגם אם קצת נרגיש שעברו מיליון שנה,", tr: "Vegam im ktzat nargish she'avru milyon shana,", en: "And even if we'll feel as though a million years have passed," },
      { he: "נמשיך, כאילו כלום, כאילו כלום לא השתנה.", tr: "Namshich, ke'ilu klum, ke'ilu klum lo hishtana.", en: "We'll continue, as if nothing— as if nothing changed at all." },
      { he: "", tr: "", en: "" },
      { he: "ובינתיים ניפגש בחלומות—", tr: "Uveintayim nipagesh bachalomot—", en: "And for now, we will meet in our dreams—" },
      { he: "אני איתך בכל שעה, בכל הנשימות;", tr: "Ani itcha bechol sha'a, bechol haneshimot;", en: "I'm with you in every hour, in the air you breathe;" },
      { he: "ואם אתה עמוק מתחת לשמיכה;", tr: "Ve'im ata amok mitachat lasmicha;", en: "And if you're underneath the covers, off to sleep;" },
      { he: "תשאיר לי את הדלת חצי פתוחה.", tr: "Tash'ir li et hadelet chatzi ptucha.", en: "Leave the door half-open; just for me." },
      { he: "", tr: "", en: "" },
      { he: "אני שולחת ידיים ארוכות;", tr: "Ani sholachat yadayim arukot;", en: "I am sending myself forth with open arms;" },
      { he: "הן מחבקות אותך עכשיו, הן מחבקות.", tr: "Hen mechabkot otcha achshav, hen mechabkot.", en: "They're wrapped around you now—they hug and guard." },
      { he: "ורק תזכור שניה לפני שאתה נרדם,", tr: "Verak tizkor shniya lifnei she'ata nirdam,", en: "And just before you fall asleep, lying curled," },
      { he: "שגעגוע הוא הדבק הכי חזק בעולם.", tr: "Shega'agu'a hu hadevek hachi chazak ba'olam.", en: "Remember longing is the strongest glue in the world." },
      { he: "", tr: "", en: "" },
      { he: "אני שולחת ידיים ארוכות;", tr: "Ani sholachat yadayim arukot;", en: "I am sending myself forth with open arms;" },
      { he: "הן מחבקות אותך עכשיו, הן מחבקות.", tr: "Hen mechabkot otcha achshav, hen mechabkot.", en: "They're wrapped around you now—they hug and guard." },
      { he: "ורק תזכור שניה לפני שאתה נרדם,", tr: "Verak tizkor shniya lifnei she'ata nirdam,", en: "And just before you fall asleep, lying curled," },
      { he: "", tr: "", en: "" },
      { he: "שגעגוע הוא הדבק הכי חזק בעולם.", tr: "Shega'agu'a hu hadevek hachi chazak ba'olam.", en: "Remember longing is the strongest glue in the world." },
      { he: "שגעגוע הוא הדבק הכי חזק בעולם.", tr: "Shega'agu'a hu hadevek hachi chazak ba'olam.", en: "Remember longing is the strongest glue in the world." },
      { he: "שגעגוע הוא הדבק הכי חזק בעולם.", tr: "Shega'agu'a hu hadevek hachi chazak ba'olam.", en: "Remember longing is the strongest glue in the world." }
    ]
  },
  {
    id: 2,
    title: "Medic's Ballad",
    titleHebrew: "בלדה לחובש",
    artist: "Yehoram Gaon",
    videoUrl: "86wdOmnW0yo",
    credits: "Written by Dan Almagor in 1956, Composed by Effie Netzer in 1968, Performed by Yehoram Gaon in 1969, Translated and Edited by Naama Ben-Dor.",
    context: "This video is part of my project to share English translations of Hebrew remembrance songs with the global community, in an effort to connect Jews throughout the diaspora in their shared pain and experiences. \"Medic's Ballad\" conveys the bravery, heroism, and self-sacrifice exemplified by so many of our fallen soldiers. It also highlights the camaraderie and unbreakable bonds that unite Israeli society, and that make each loss all the more tragic.",
    lyrics: [
      { he: "הם התקדמו לאט. הכל היה רגוע;", tr: "Hem hitkadmu le'at. Hakol haya rague'a;", en: "They proceeded onward slowly. Everything was calm;" },
      { he: "מנגד הנהר וגומא מרשרש.", tr: "Mineged hanahar vegome merashesh.", en: "The reeds rustled across the river." },
      { he: "פתאום רעם ברק, אחד צעק: \"פצוע!\"", tr: "Pit'om ra'am barak, echad tza'ak: \"Patzu'a!\"", en: "Suddenly thunder and lightning, someone shouted: \"wounded!\"" },
      { he: "\"אני כבר בא\" — ענה לו החובש.", tr: "\"Ani kvar ba\" — ana lo hachovesh.", en: "\"I'm already on my way\" — replied the medic." },
      { he: "", tr: "", en: "" },
      { he: "\"עלינו על מוקש!\" — צעק אז הפצוע,", tr: "\"Alinu al mokesh!\" — tza'ak az hapatzu'a,", en: "\"We stepped on a mine!\" — the wounded man shouted then," },
      { he: "\"אני כאן, לצידך\" — ענה לו החובש.", tr: "\"Ani kan, letzidcha\" — ana lo hachovesh.", en: "\"I'm right here, by your side.\" — the medic answered him." },
      { he: "ברד של אש ניתך; ברד כבד קטוע,", tr: "Barad shel esh nitach; barad kaved katu'a,", en: "A hail of fire poured; heavy, fragmented hail," },
      { he: "מעבר לנהר, לגומא הרוחש.", tr: "Me'ever lanehar, lagome harochesh.", en: "Across the river, where the reeds rustled." },
      { he: "\"השאירו אותי כאן!\" — ביקש אז הפצוע,", tr: "\"Hash'iru oti kan!\" — bikesh az hapatzu'a,", en: "\"Leave me here!\" — the wounded man then begged," },
      { he: "\"עזוב שטויות.\" — ענה לו החובש.", tr: "\"Azov shtuyot.\" — ana lo hachovesh.", en: "\"Stop with the nonsense.\" — the medic replied." },
      { he: "\"תציל את עצמך!\" — ביקש אז הפצוע.", tr: "\"Tatzil et atzmcha!\" — bikesh az hapatzu'a.", en: "\"Save yourself!\" — the wounded man pleaded." },
      { he: "\"אני נשאר איתך.\" — ענה לו החובש.", tr: "\"Ani nish'ar itcha.\" — ana lo hachovesh.", en: "\"I'm staying here with you.\" — the medic answered him." },
      { he: "", tr: "", en: "" },
      { he: "והם נותרו שניהם, והשדה פתוח.", tr: "Vehem notru shneihem, vehasadeh patuach.", en: "And the two of them remained, and the field was open." },
      { he: "והם נותרו שניהם, והם גלויים לאש.", tr: "Vehem notru shneihem, vehem gluyim la'esh.", en: "And the two of them remained, and they were exposed to fire." },
      { he: "", tr: "", en: "" },
      { he: "\"אנחנו אבודים!\" — מילמל אז הפצוע,", tr: "\"Anachnu avudim!\" — milmel az hapatzu'a,", en: "\"We're a lost cause!\" — the wounded man then muttered," },
      { he: "\"אחוז בי טוב.\" — ענה לו החובש.", tr: "\"Echoz bi tov.\" — ana lo hachovesh.", en: "\"Hold tight onto me.\" — the medic responded." },
      { he: "\"נפצעת גם אתה!\" — מילמל אז הפצוע", tr: "\"Niftzata gam ata!\" — milmel az hapatzu'a", en: "\"You were also wounded!\" — the wounded man then mumbled," },
      { he: "\"עזוב, זה לא נורא.\" — ענה לו החובש.", tr: "\"Azov, ze lo nora.\" — ana lo hachovesh.", en: "\"Forget it, it's not serious.\" — the medic answered him." },
      { he: "", tr: "", en: "" },
      { he: "האש כבדה, כבדה! קשה, קשה לנוע.", tr: "Ha'esh kvedah, kvedah! Kasheh, kasheh lanu'a.", en: "The fire is heavy, heavy! It's difficult to move." },
      { he: "רק לא להתייאש, רק לא להתייאש,", tr: "Rak lo lehity a'esh, rak lo lehity a'esh,", en: "Just don't give up, just don't give up!" },
      { he: "", tr: "", en: "" },
      { he: "\"אזכור אותך תמיד.\" — נשבע אז הפצוע.", tr: "\"Ezkor otcha tamid.\" — nishba az hapatzu'a.", en: "\"I'll remember you forever.\" — the wounded man then swore." },
      { he: "\"רק לא ליפול.\" — מילמל אז החובש.", tr: "\"Rak lo lipol.\" — milmel az hachovesh.", en: "\"Just don't fall\" — the medic muttered then." },
      { he: "\"שלך עד יום מותך!\"— נשבע אז הפצוע.", tr: "\"Shelcha ad yom motcha!\" — nishba az hapatzu'a.", en: "\"I'm yours until you die\" — the wounded man then swore." },
      { he: "\"היום הוא יום מותי.\" — ענה לו החובש.", tr: "\"Hayom hu yom moti.\" — ana lo hachovesh.", en: "\"Today's my day of death\" — the medic answered him." },
      { he: "", tr: "", en: "" },
      { he: "פתאום ענן אבק, פתאום עלתה הרוח,", tr: "Pit'om anan avak, pit'om alta haruach,", en: "Suddenly, a cloud of dust, suddenly the wind swept up," },
      { he: "וצל על הקרקע, והוא קרב, רועש.", tr: "Vetzel al hakarka, vehu karev, ro'esh.", en: "And a shadow on the ground, and it approached, loudly." },
      { he: "\"ניצלנו! הם באים!\" — ייבב אז הפצוע;", tr: "\"Nitzalnu! Hem ba'im!\" — yibev az hapatzu'a;", en: "\"We're rescued! They're coming!\" — the wounded man then shrieked;" },
      { he: "אך לא שמע מילה מן החובש.", tr: "Ach lo shama mila min hachovesh.", en: "But he didn't hear a word from the medic." },
      { he: "", tr: "", en: "" },
      { he: "\"אחי, אחי שלי!\" — ייבב אז הפצוע.", tr: "\"Achi, achi sheli!\" — yibev az hapatzu'a.", en: "\"My brother, my brother!\" — the wounded man then wailed." },
      { he: "מעבר לנהר הגומא מרשרש.", tr: "Me'ever lanehar hagome merashesh.", en: "Across the river, the reeds rustled." },
      { he: "", tr: "", en: "" },
      { he: "\"אחי, אחי שלי—\"", tr: "\"Achi, achi sheli—\"", en: "\"My brother, my brother\" —" },
      { he: "\"אחי, אחי שלי—\"", tr: "\"Achi, achi sheli—\"", en: "\"My brother, my brother\" —" },
      { he: "\"אחי!\"", tr: "\"Achi!\"", en: "\"My brother!\"" }
    ]
  },
  {
    id: 3,
    title: "Where Are You",
    titleHebrew: "אייכה",
    artist: "Shuli Rand",
    videoUrl: "SbYYJA1gFkk",
    credits: "Written and performed by Shuli Rand in 2008. Translated and Edited by Naama Ben-Dor. The images generated for this video were created using Gemini AI.",
    context: "This video is part of my project to share English translations of Hebrew remembrance songs with the global community, in an effort to connect Jews throughout the diaspora in their shared pain and experiences. \"אייכה\" symbolizes the agonizing clash between faith and misery, and is sometimes performed at Holocaust Remembrance Day ceremonies and other memorial events.",
    lyrics: [
      { he: "ריבונו של עולם, אם נדבר גלויות,", tr: "Ribono shel Olam, im nedaber gluyot,", en: "Master of the universe, if we're speaking frankly," },
      { he: "לפעמים אין לי כוח בעולמך להיות.", tr: "Lif'amim ein li ko'ach be'olamcha lihiyot.", en: "Sometimes I lack the strength to remain in your world." },
      { he: "אנה מפניך אסתתר?", tr: "Ana mipanecha estater?", en: "Where could I conceal myself from your gaze?" },
      { he: "מה אטען?", tr: "Ma et'an?", en: "What would I claim?" },
      { he: "מה אצטדק?", tr: "Ma etztadek?", en: "How would I justify myself?" },
      { he: "מה אדבר?", tr: "Ma adaber?", en: "What would I say?" },
      { he: "", tr: "", en: "" },
      { he: "חנון ורחום, הן לפניך גלוי", tr: "Chanun verachum, hen lefanecha galui", en: "Merciful and gracious, indeed all is revealed to You." },
      { he: "כאן יהודי שעל חוט—", tr: "Kan yehudi she'al chut—", en: "Before You is a Jew on a string—" },
      { he: "השערה הוא תלוי.", tr: "Hasa'ara hu talui.", en: "Hanging by a hair." },
      { he: "נלחם בעצבות;", tr: "Nilcham ba'atzvut;", en: "Wrestling the sadness;" },
      { he: "בייאוש המכרסם—כתולעת.", tr: "Baye'ush hamecharsem—ketola'at.", en: "The despair that gnaws—like a worm." },
      { he: "השמחה נסתלקה ממני—", tr: "Hasimcha nistalka mimeni—", en: "The joy has been extinguished in me—" },
      { he: "וגם הדעת.", tr: "Vegam hada'at.", en: "And so has reason." },
      { he: "", tr: "", en: "" },
      { he: "קולות מהעבר לוחשים לי לעצור,", tr: "Kolot meha'avar lochashim li la'atzor,", en: "Voices from the past whisper at me to quit," },
      { he: "אבל אני מוסיף בחושך לחתור,", tr: "Aval ani mosif bachoshech lachtor,", en: "But I continue to row in the darkness." },
      { he: "ושואל;", tr: "Vesho'el;", en: "And I ask;" },
      { he: "ומבקש;", tr: "Umevakesh;", en: "And I plead;" },
      { he: "איה—", tr: "Aye—", en: "Where—" },
      { he: "איה—", tr: "Aye—", en: "Where—" },
      { he: "או, אייכה?", tr: "O, Ayeka?", en: "Where are You?" },
      { he: "", tr: "", en: "" },
      { he: "איה—", tr: "Aye—", en: "Where—" },
      { he: "איה?", tr: "Aye?", en: "Where?" },
      { he: "או, אייכה?", tr: "O, Ayeka?", en: "Where are You?" },
      { he: "אייכה?", tr: "Ayeka?", en: "Where are You?" },
      { he: "", tr: "", en: "" },
      { he: "אותו זקן וכסיל שולח בי חיצים,", tr: "Oto zaken uchesil shole'ach bi chitzim,", en: "That same old fool sends arrows out at me." },
      { he: "אני הולך וכושל;", tr: "Ani holech vechoshel;", en: "I walk and stumble;" },
      { he: "הוא הולך ומעצים.", tr: "Hu holech uma'atzim.", en: "He continues and intensifies." },
      { he: "נשמה קדושה אל נא תבכי, שבורת-כנף.", tr: "Neshama kedosha al na tivki, shvurat-kanaf.", en: "Holy soul do not weep, broken-winged." },
      { he: "הן, תעידי עליי כמה הייתי נכסף.", tr: "Hen, ta'idi alai kama hayiti nichsaf.", en: "Indeed, you would attest how greatly I've yearned." },
      { he: "", tr: "", en: "" },
      { he: "כשסודות מהעבר פקדו עליי לעצור,", tr: "Keshesodot meha'avarakdu alai la'atzor,", en: "When secrets from the past commanded me to quit," },
      { he: "אבל אני מוסיף, בחושך לחתור.", tr: "Aval ani mosif, bachoshech lachtor.", en: "But I continue to row in the darkness." },
      { he: "ושואל;", tr: "Vesho'el;", en: "And I ask;" },
      { he: "ומבקש;", tr: "Umevakesh;", en: "And I plead;" },
      { he: "איה—", tr: "Aye—", en: "Where—" },
      { he: "איה—", tr: "Aye—", en: "Where—" },
      { he: "או, אייכה?", tr: "O, Ayeka?", en: "Where are You?" },
      { he: "", tr: "", en: "" },
      { he: "איה—", tr: "Aye—", en: "Where, where, where are You?" },
      { he: "איה—", tr: "Aye—", en: "Where, where, where are You?" },
      { he: "אייכה?", tr: "Ayeka?", en: "Where are You?" },
      { he: "אייכה?", tr: "Ayeka?", en: "Where are You?" },
      { he: "", tr: "", en: "" },
      { he: "בסופו של יום, הן אפלט אל החוף,", tr: "Besofo shel yom, hen ipalet el hachof,", en: "At the end of the day, I will be hurled onto the sand." },
      { he: "האדמה הרחומה אותי אליה תאסוף.", tr: "Ha'adama harachuma oti eleiha te'esof.", en: "The merciful earth will take me in." },
      { he: "ואז אצעק;", tr: "Ve'az etz'ak;", en: "And then I will yell;" },
      { he: "ואצטדק;", tr: "Ve'etztadek;", en: "And justify myself;" },
      { he: "ואספר—", tr: "Va'asaper—", en: "And recount—" },
      { he: "איך בחושך הזה הייתי חותר,", tr: "Eich bachoshech hazeh hayiti choter,", en: "How I used to row through this darkness," },
      { he: "ושואל, ומבקש, וכוסף...", tr: "Vesho'el, umevakesh, vechosef...", en: "And ask, and plead, and yearn…" },
      { he: "אייכה?", tr: "Ayeka?", en: "Where are You?" }
    ]
  },
  {
    id: 4,
    title: "In Our Kindergarten",
    titleHebrew: "אצלנו בגן",
    artist: "Shayli Atari",
    videoUrl: "h7lxLgEQsOw",
    credits: "Written and composed by Yiftach Kerzner in memory of his friend, Tom Farkash, who fell in the Second Lebanon War. The song was performed by Shayli Atari in 2014. Translated by Naama Ben-Dor.",
    context: "Etzlenu BaGan (אצלנו בגן) was written and composed by Yiftach Kerzner in memory of his friend, Tom Farkash, who fell in the Second Lebanon War. The song was performed by Shayli Atari in 2014, during Operation Protective Edge, but has since taken on added significance, as Atari's husband was later murdered on Oct. 7, 2023, while protecting his wife and one-month-old daughter from Hamas terrorists who infiltrated into their home.",
    lyrics: [
      { he: "אצלנו בגן יש המון ילדים", tr: "Etzlenu bagan yesh hamon yeladim", en: "At our kindergarten, there are many kids," },
      { he: "את חלקם אני אוהב", tr: "Et chelkam ani ohev", en: "Some of them—I like" },
      { he: "את חלקם אני לא מכיר", tr: "Et chelkam ani lo makir", en: "Some—I don't know." },
      { he: "אבל מי לא שמע על האומץ של רן", tr: "Aval mi lo shama al ha'ometz shel Ran", en: "But who hasn't heard of Ran's courage?" },
      { he: "הוא הכי מהיר בחול הוא הכי חזק בגן", tr: "Hu hachi mahir bachol hu hachi chazak bagan", en: "He's the fastest in the sand, he's the strongest in the kindergarten" },
      { he: "אבל יש לו סוד אחד שפחד הוא לגלות", tr: "Aval yesh lo sod echad shepached hu legalot", en: "But he has this one secret, that he's scared to reveal;" },
      { he: "שהוא כל כך מאוהב באחת הילדות", tr: "Shehu kol kach me'ohav be'achat hayeladot", en: "That he's madly in love with one of the girls." },
      { he: "", tr: "", en: "" },
      { he: "אז בלילות קרים", tr: "Az balaylot karim", en: "So on cold nights," },
      { he: "עם פנס מתחת לשמיכה הם מדברים", tr: "Im panas mitachat lasmicha hem medabrim", en: "With a flashlight under the covers, they talk" },
      { he: "והוא מגלה לה מה היא בשבילו—כל עולמו", tr: "Vehu megaleh la ma hi bishvilo—kol olamo", en: "And he confesses to her what she means to him—his entire world." },
      { he: "מוגן מתחת לשמיכה", tr: "Mugan mitachat lasmicha", en: "Protected underneath the blanket." },
      { he: "", tr: "", en: "" },
      { he: "אצלנו בגן יש הרבה חבורות", tr: "Etzlenu bagan yesh harbeh chavurot", en: "At our kindergarten there are many cliques" },
      { he: "יש כאלה נחשבים יש כאלה שפחות", tr: "Yesh ka'ele nechshavim yesh ka'ele shepachot", en: "Some are considered \"cool,\" others not as much." },
      { he: "אבל מי לא שמע על קופצי הנדנדות", tr: "Aval mi lo shama al koftzei hanadnedot", en: "But who hasn't heard of the Swing-Jumpers" },
      { he: "מריעים להם כפיים מלמדים אותם לנחות", tr: "Meri'im lahem kapayim melamdim otam linchot", en: "They are showered with applause, they are taught how to land" },
      { he: "מורמים על נס הדגל גאוות כל האזור", tr: "Muramim al nes hadegel ga'avat kol ha'ezor", en: "They are raised up with the flag, the pride of the entire region" },
      { he: "רק לפעמים כשהם קופצים רחוק הם שוכחים לחזור", tr: "Rak lif'amim kshehem koftzim rachok hem shochechim lachzor", en: "Except—sometimes when they jump too far, they forget to return." },
      { he: "", tr: "", en: "" },
      { he: "אז בלילות קרים", tr: "Az balaylot karim", en: "So on cold nights" },
      { he: "עם פנס מתחת לשמיכה הם מדברים", tr: "Im panas mitachat lasmicha hem medabrim", en: "With a flashlight under the covers they talk" },
      { he: "והוא מגלה לה מה היא בשבילו—כל עולמו", tr: "Vehu megaleh la ma hi bishvilo—kol olamo", en: "And he confesses to her what she means to him—his entire world. Protected underneath the blanket." },
      { he: "מוגן מתחת לשמיכה", tr: "Mugan mitachat lasmicha", en: "" },
      { he: "", tr: "", en: "" },
      { he: "אצלנו בגן נפרדים בשמחה", tr: "Etzlenu bagan nifradim besimcha", en: "At our kindergarten, we part with a smile" },
      { he: "כי היום לא ארוך ונפגשים שוב מחר", tr: "Ki hayom lo aroch venifgashim shuv machar", en: "Because the day isn't long, and we'll meet again tomorrow" },
      { he: "חוץ מאלה שפתאום לא חוזרים יותר לגן", tr: "Chutz me'ele shepit'om lo chozrim yoter lagan", en: "Except for those who suddenly stop returning to the kindergarten" },
      { he: "אמרו לי שהם רק עברו דירה מעבר לענן", tr: "Amru li shehem rak avru dira me'ever la'anan", en: "I was told that they just moved to a new home, on the other side of the clouds." },
      { he: "", tr: "", en: "" },
      { he: "אז בלילות קרים", tr: "Az balaylot karim", en: "So on cold nights" },
      { he: "עם פנס מתחת לשמיכה הם מדברים", tr: "Im panas mitachat lasmicha hem medabrim", en: "With a flashlight under the covers they talk" },
      { he: "והוא מגלה לה מה היא בשבילו", tr: "Vehu megaleh la ma hi bishvilo", en: "And he confesses to her what she means to him —" },
      { he: "והיא בוכה שהוא מציע לה להיות—כל עולמו", tr: "Vehi bocha shehu metzia la lihiyot—kol olamo", en: "And she cries when he proposes that she be—his entire world," },
      { he: "בערב שלפני המלחמה.", tr: "Ba'erev shelifnei hamilchama.", en: "On the evening before the war." },
      { he: "", tr: "", en: "" },
      { he: "אצלנו בגדוד, יש המון ילדים", tr: "Etzlenu bagdud, yesh hamon yeladim", en: "In our battalion, there are many kids," },
      { he: "את חלקם אני אוהב", tr: "Et chelkam ani ohev", en: "Some of them—I like" },
      { he: "את חלקם אני לא אכיר", tr: "Et chelkam ani lo akir", en: "Some—I'll never meet." }
    ]
  },
  {
    id: 5,
    title: "The Wheat Grows Again",
    titleHebrew: "החיטה צומחת שוב",
    artist: "Chava Alberstein",
    videoUrl: "m3p_TnEhyto",
    credits: "Written by Dorit Tzameret in 1974, Melody composed by Haim Barkani in 1978, Performed by Chava Alberstein in 1983, Translated to English by Naama Ben-Dor.",
    context: "The Wheat Still Grows Again was written by Dorit Tzameret in 1974, after eleven members of her kibbutz were killed in the Yom Kippur War. The melody was later composed by Haim Barkani in 1978. This rendition was performed by Chava Alberstein in 1983.",
    lyrics: [
      { he: "שדות שפוכים הרחק", tr: "Sadot shfuchim harchek", en: "Fields spill out into the distance," },
      { he: "מאופק ועד סף", tr: "Me'ofek ve'ad saf", en: "Until the edge of the horizon" },
      { he: "וחרובים וזית וגלבוע -", tr: "Vecharuvim vezayit veGilboa -", en: "And carobs, and olives, and the Gilboa—" },
      { he: "ואל ערבו העמק נאסף", tr: "Ve'el arbo ha'emek ne'esaf", en: "And the valley is engulfed by the evening." },
      { he: "ביופי שעוד לא היה כמוהו.", tr: "Beyofi she'od lo haya kamohu.", en: "With beauty that exceeds all that came before." },
      { he: "", tr: "", en: "" },
      { he: "זה לא אותו העמק, זה לא אותו הבית,", tr: "Ze lo oto ha'emek, ze lo oto habayit,", en: "This is not the same valley, this is not the same home" },
      { he: "אתם אינכם ולא תוכלו לשוב", tr: "Atem einchem velo tuchlu lashuv", en: "You all are gone, and you can never return" },
      { he: "השביל עם השדרה, ובשמיים עיט", tr: "Hashvil im hasdera, uvashamayim ayit", en: "The path with the boulevard, and in the sky–an eagle" },
      { he: "אך החיטה צומחת שוב", tr: "Ach hachita tzomachat shuv", en: "And yet, the wheat grows again." },
      { he: "", tr: "", en: "" },
      { he: "מן העפר המר העיריות עולות", tr: "Min ha'afar hamar ha'iriyot olot", en: "From beneath the bitter ashes, the asphodels bloom" },
      { he: "ועל הדשא ילד וכלבו", tr: "Ve'al hadeshe yeled uchalbo", en: "And on the grass, a boy and his dog" },
      { he: "מואר החדר ויורדים לילות", tr: "Mu'ar hacheder veyordim leilot", en: "The well-lit room radiates as the nights fall" },
      { he: "על מה שבו ומה שבליבו", tr: "Al ma shebo u'mah shebelibo", en: "Over that which lies inside, and within his heart" },
      { he: "", tr: "", en: "" },
      { he: "זה לא אותו העמק, זה לא אותו הבית,", tr: "Ze lo oto ha'emek, ze lo oto habayit,", en: "This is not the same valley, this is not the same home" },
      { he: "אתם אינכם ולא תוכלו לשוב", tr: "Atem einchem velo tuchlu lashuv", en: "You all are gone, and you can never return" },
      { he: "השביל עם השדרה, ובשמיים עיט -", tr: "Hashvil im hasdera, uvashamayim ayit -", en: "The path with the boulevard, and in the sky–an eagle" },
      { he: "אך החיטה צומחת שוב", tr: "Ach hachita tzomachat shuv", en: "And yet, the wheat grows again." },
      { he: "", tr: "", en: "" },
      { he: "וכל מה שהיה אולי יהיה לעד", tr: "Vechol ma shehaya ulai yihyeh la'ad", en: "And everything that was, perhaps will always be" },
      { he: "זרח השמש שוב השמש בא", tr: "Zarach hashemesh shuv hashemesh ba", en: "The sun rose; again, the sun returns" },
      { he: "עוד השירים שרים אך איך יוגד", tr: "Od hashirim sharim ach eich yugad", en: "And still, the songs are sung, but how can they convey" },
      { he: "כל המכאוב וכל האהבה", tr: "Kol hamach'ov vechol ha'ahava", en: "The depths of the pain, and the depths of the love." },
      { he: "", tr: "", en: "" },
      { he: "הן זה אותו העמק, הן זה אותו הבית", tr: "Hen ze oto ha'emek, hen ze oto habayit", en: "Yes, this is the same valley, yes, this is the same home" },
      { he: "אבל אתם הן לא תוכלו לשוב", tr: "Aval atem hen lo tuchlu lashuv", en: "But you—yes, you can never return" },
      { he: "ואיך קרה, ואיך קרה? ואיך קורה עדיין", tr: "Ve'eich kara, ve'eich kara? Ve'eich koreh adayin", en: "And how did it happen, and how did it happen? And how can it still be" },
      { he: "שהחיטה צומחת שוב?", tr: "Shehachita tzomachat shuv?", en: "That the wheat grows again?" },
      { he: "ואיך קרה, ואיך קרה ואיך קורה עדיין…", tr: "Ve'eich kara, ve'eich kara ve'eich koreh adayin…", en: "And how did it happen, and how did it happen? And how can it still be…" },
      { he: "שהחיטה,", tr: "Shehachita,", en: "That the wheat," },
      { he: "שהחיטה צומחת שוב.", tr: "Shehachita tzomachat shuv.", en: "That the wheat grows again." }
    ]
  },
  {
    id: 6,
    title: "Dance",
    titleHebrew: "תרקדי",
    artist: "Osher Cohen",
    videoUrl: "8_3BYyW2zT0",
    credits: "Lyrics and music: Osher Cohen, Nadav (Navi) Aharoni. Arrangement and musical production: Nadav (Navi) Aharoni. Translated by Naama Ben-Dor.",
    context: "Dance (תרקדי) was written and composed by Osher Cohen and Nadav (Navi) Aharoni in memory of the victims killed on October 7, 2023 at the Nova music festival massacre in Kibbutz Re'im.",
    lyrics: [
      { he: "תרקדי.", tr: "Tirkedi.", en: "Dance." },
      { he: "השירים עושים לך טוב.", tr: "Hashirim osim lach tov.", en: "The songs will do you good." },
      { he: "כולם חברים כאן,", tr: "Kulam chaverim kan,", en: "We are all friends here," },
      { he: "אחים אחיות.", tr: "Achim achayot.", en: "Brothers and sisters." },
      { he: "", tr: "", en: "" },
      { he: "תרקדי.", tr: "Tirkedi.", en: "Dance." },
      { he: "נו תעופי בלי לחשוב.", tr: "Nu ta'ufi bli lachshov.", en: "Go on and fly, without thinking." },
      { he: "פה ושם תירגעי קצת.", tr: "Po vesham tirge'i ktzat.", en: "Here and there calm yourself a little." },
      { he: "תשמרי לך כוחות.", tr: "Tishmeri lach kochot.", en: "Save your strengths." },
      { he: "", tr: "", en: "" },
      { he: "אולי תברחי… אין לנו זמן.", tr: "Ulai tivrachi… Ein lanu zman.", en: "Maybe you will escape… We don't have time." },
      { he: "אולי תברחי… הם עוד מעט כאן.", tr: "Ulai tivrachi… Hem od me'at kan.", en: "Maybe you will escape… They are almost here." },
      { he: "", tr: "", en: "" },
      { he: "ואם תשמעי—", tr: "Ve'im tishme'i—", en: "And If you hear—" },
      { he: "צליפות הדשא,", tr: "Tzlifot hadeshe,", en: "The whipping of grass," },
      { he: "חוטי עשן,", tr: "Chutei ashan,", en: "The strings of smoke," },
      { he: "תרוצי מהר; את נגד הזמן.", tr: "Tarutzi maher; at neged hazman.", en: "Run away quick; time is against you." },
      { he: "", tr: "", en: "" },
      { he: "שריקות ההדף,", tr: "Shrikot hahedef,", en: "The whistles of the blasts," },
      { he: "עמודי הענן,", tr: "Amudei ha'anan,", en: "The pillars of clouds," },
      { he: "אל תעצרי, אני בדרך,", tr: "Al ta'atzri, ani baderech,", en: "Don't stop, I am on my way," },
      { he: "ואם עייפת—", tr: "Ve'im ayaft—", en: "And if you've tired out—" },
      { he: "", tr: "", en: "" },
      { he: "את בטח רוקדת לך שם.", tr: "At betach rokedet lach sham.", en: "You're probably already up there, dancing." },
      { he: "את בטח רוקדת לך שם.", tr: "At betach rokedet lach sham.", en: "You're probably already up there, dancing." },
      { he: "", tr: "", en: "" },
      { he: "תרקדי.", tr: "Tirkedi.", en: "Dance." },
      { he: "אל תדאגי, זה הנוף.", tr: "Al tid'agi, ze hanof.", en: "Don't worry, this is the view." },
      { he: "שכלום לא יזיז לך,", tr: "Sheklum lo yaziz lach,", en: "Don't let anything stir you," },
      { he: "גם לא אש הקרבות.", tr: "Gam lo esh hakravot.", en: "Not even the fires of battle." },
      { he: "", tr: "", en: "" },
      { he: "תרקדי.", tr: "Tirkedi.", en: "Dance." },
      { he: "נתראה בקרוב.", tr: "Nitra'eh bekarov.", en: "We will meet again soon." },
      { he: "כולם מחכים לך,", tr: "Kulam mechakim lach,", en: "Everyone is waiting for you," },
      { he: "רק עוד כמה שבתות.", tr: "Rak od kama shabatot.", en: "It'll only be a few more Shabbats." },
      { he: "", tr: "", en: "" },
      { he: "אל תדאגי,", tr: "Al tid'agi,", en: "Don't worry," },
      { he: "ייקח לנו זמן.", tr: "Yikach lanu zman.", en: "It will take us a while." },
      { he: "אל תדאגי,", tr: "Al tid'agi,", en: "Don't worry," },
      { he: "את עוד מעט כאן.", tr: "At od me'at kan.", en: "You are almost here." },
      { he: "", tr: "", en: "" },
      { he: "ואם תשמעי—", tr: "Ve'im tishme'i—", en: "And If you hear—" },
      { he: "צליפות הדשא,", tr: "Tzlifot hadeshe,", en: "The whipping of grass," },
      { he: "חוטי עשן,", tr: "Chutei ashan,", en: "The strings of smoke," },
      { he: "תרוצי מהר; את נגד הזמן.", tr: "Tarutzi maher; at neged hazman.", en: "Run away quick; time is against you." },
      { he: "", tr: "", en: "" },
      { he: "שריקות ההדף,", tr: "Shrikot hahedef,", en: "The whistles of the blasts," },
      { he: "עמודי הענן,", tr: "Amudei ha'anan,", en: "The pillars of clouds," },
      { he: "אל תעצרי, אני בדרך,", tr: "Al ta'atzri, ani baderech,", en: "Don't stop, I am on my way," },
      { he: "ואם עייפת—", tr: "Ve'im ayaft—", en: "And if you've tired out—" },
      { he: "", tr: "", en: "" },
      { he: "את בטח רוקדת לך שם.", tr: "At betach rokedet lach sham.", en: "You're probably already up there, dancing." },
      { he: "את בטח רוקדת לך שם.", tr: "At betach rokedet lach sham.", en: "You're probably already up there, dancing." },
      { he: "את בטח רוקדת לך שם.", tr: "At betach rokedet lach sham.", en: "You're probably already up there, dancing." },
      { he: "לה לה לה לה לה לה", tr: "La la la la la la", en: "" },
      { he: "", tr: "", en: "" },
      { he: "צליפות הדשא,", tr: "Tzlifot hadeshe,", en: "Whipping of grass," },
      { he: "חוטי העשן,", tr: "Chutei ha'ashan,", en: "The strings of smoke," },
      { he: "תרוצי מהר,", tr: "Tarutzi maher,", en: "Run away quick," },
      { he: "את נגד הזמן.", tr: "At neged hazman.", en: "Time is against you." },
      { he: "", tr: "", en: "" },
      { he: "שריקות ההדף,", tr: "Shrikot hahedef,", en: "The whistles of the blasts," },
      { he: "עמודי הענן,", tr: "Amudei ha'anan,", en: "The pillars of clouds," },
      { he: "אל תעצרי, אני בדרך,", tr: "Al ta'atzri, ani baderech,", en: "Don't stop, I am on my way," },
      { he: "ואם עייפת—", tr: "Ve'im ayaft—", en: "And if you've tired out—" },
      { he: "", tr: "", en: "" },
      { he: "שריטות הנפש,", tr: "Sritot hanefesh,", en: "The wounds to your soul," },
      { he: "עוד יהיו לך מקלט,", tr: "Od yihyu lach miklat,", en: "Will be your refuge," },
      { he: "אל תעצרי, כי את לוחמת,", tr: "Al ta'atzri, ki at lochemet,", en: "Don't stop, because you are a fighter," },
      { he: "ואם עייפת—", tr: "Ve'im ayaft—", en: "And if you've tired yourself out—" },
      { he: "", tr: "", en: "" },
      { he: "את בטח רוקדת לך שם.", tr: "At betach rokedet lach sham.", en: "You're probably already up there, dancing." }
    ]
  },
  {
    id: 7,
    title: "Perach (Flower)",
    titleHebrew: "פרח",
    artist: "Yehuda Poliker",
    videoUrl: "icI7Hmrr7YM",
    credits: "Written by Tzruya Lahav and composed by Yehuda Poliker in 1985. Translated by Naama Ben-Dor.",
    context: "\"Perach\" was written by Tzruya Lahav and composed by Yehuda Poliker in 1985, in memory of the victims of the Ras Burqa massacre. On October 5th, 1985, an Egyptian soldier opened fire at a group of Israeli tourists at a beach resort located in the Ras Burqa bay on the Sinai peninsula. He murdered three adults and four young children.",
    lyrics: [
      { he: "שם, בעפר ותכלת,", tr: "Sham, be'afar utchelet,", en: "There, in the dust and sky," },
      { he: "חלקת שלום ישנה.", tr: "Chelkat shalom yeshena.", en: "Lies a grave of peace." },
      { he: "נומי פרח, נומי.", tr: "Numi perach, numi.", en: "Sleep, flower, sleep." },
      { he: "נומי, ילדה קטנה.", tr: "Numi, yalda ktana.", en: "Sleep, little girl." },
      { he: "", tr: "", en: "" },
      { he: "את החיים—לקחו לך;", tr: "Et hachayim—lakchu lach;", en: "Your life—they stole from you;" },
      { he: "הו, מלחמות קדושות.", tr: "Ho, milchamot kedoshot.", en: "Oh, holy wars." },
      { he: "מלאכים בכו לך—", tr: "Mal'achim bachu lach—", en: "Angels wept for you—" },
      { he: "בעיניים יבשות.", tr: "Be'einayim yeveshot.", en: "With eyes devoid of tears." },
      { he: "", tr: "", en: "" },
      { he: "את חיוכך, תינוקת;", tr: "Et chiyucheck, tinoket;", en: "Your smile, baby girl;" },
      { he: "קברו באדמה,", tr: "Kavru ba'adama,", en: "They buried in the earth." },
      { he: "איך צומח שקט,", tr: "Eich tzome'ach sheket,", en: "How does silence bloom," },
      { he: "מתוך המהומה?", tr: "Mitoch hamehuma?", en: "Out of the chaos?" },
      { he: "", tr: "", en: "" },
      { he: "מי שלחץ על הדק—", tr: "Mi shelachatz al hedek—", en: "He, who pulled the trigger—" },
      { he: "דם, את ליבו מכתים.", tr: "Dam, et libo machtim.", en: "Taints his heart with blood." },
      { he: "במלחמות לצדק,", tr: "Bemilchamot letzedek,", en: "In battles for justice," },
      { he: "גם ילדים מתים.", tr: "Gam yeladim metim.", en: "Even children are killed." },
      { he: "", tr: "", en: "" },
      { he: "את החיים—לקחו לך;", tr: "Et hachayim—lakchu lach;", en: "Your life—they stole from you;" },
      { he: "הו, מלחמות קדושות.", tr: "Ho, milchamot kedoshot.", en: "Oh, holy wars." },
      { he: "מלאכים בכו לך—", tr: "Mal'achim bachu lach—", en: "Angels wept for you—" },
      { he: "בעיניים יבשות.", tr: "Be'einayim yeveshot.", en: "With dry eyes." },
      { he: "", tr: "", en: "" },
      { he: "שם, בעפר ותכלת,", tr: "Sham, be'afar utchelet,", en: "There, in the dust and sky," },
      { he: "חלקת שלום ישנה.", tr: "Chelkat shalom yeshena.", en: "A grave of peace lies asleep." },
      { he: "נומי פרח, נומי.", tr: "Numi perach, numi.", en: "Sleep, flower, sleep." },
      { he: "נומי, ילדה קטנה.", tr: "Numi, yalda ktana.", en: "Sleep, little girl." },
      { he: "", tr: "", en: "" },
      { he: "את החיים—לקחו לך.", tr: "Et hachayim—lakchu lach.", en: "Of your life—they robbed you;" },
      { he: "הו, מלחמות קדושות.", tr: "Ho, milchamot kedoshot.", en: "Oh, holy wars." },
      { he: "מלאכים בכו לך—", tr: "Mal'achim bachu lach—", en: "Angels wept for you—" },
      { he: "בעיניים יבשות.", tr: "Be'einayim yeveshot.", en: "With dry eyes." },
      { he: "", tr: "", en: "" },
      { he: "וחלומך ברוח,", tr: "Vachaloméch baruach,", en: "And your dream in the wind," },
      { he: "חרוז למנגינה.", tr: "Charuz lamangina.", en: "Rhymes with the melody." },
      { he: "נומי פרח, נומי.", tr: "Numi perach, numi.", en: "Sleep, flower, sleep." },
      { he: "נומי ילדה קטנה.", tr: "Numi yalda ktana.", en: "Sleep, little girl." }
    ]
  },
  {
    id: 8,
    title: "Child, Father, and Mother",
    titleHebrew: "ילד ואבא ואמא",
    artist: "Harel Skat and Ilai Botner",
    videoUrl: "qNUAYbkew18",
    credits: "Written and composed by Ilai Botner, Performed by Harel Skat and the children of the IDF Widows and Orphans Organization. Translated by Naama Ben-Dor.",
    context: "A touching song about loss and hope, performed by children who have lost parents in service to Israel. The song speaks of the eternal connection between loved ones, separated by distance but never truly apart.",
    lyrics: [
      { he: "בכל פעם כששמש שוקעת", tr: "Bechol pa'am kshe shemesh shoka'at", en: "Every time the sun sets" },
      { he: "כשמטוס בשמיים עובר", tr: "Kshematos bashamayim over", en: "And a plane passes through the sky" },
      { he: "אתה שם בכל אלה, שומר מלמעלה", tr: "Ata sham bechol ele, shomer milemala", en: "You are there—in all these moments, protecting from above" },
      { he: "שכלום לא יהיה כאן חסר", tr: "Sheklum lo yihyeh kan chaser", en: "Ensuring that nothing here will be missing." },
      { he: "", tr: "", en: "" },
      { he: "וכשגשם ראשון מגיע", tr: "Uchshegeshem rishon magi'a", en: "And when the first rainfall arrives," },
      { he: "והלילה אפל ומנוכר", tr: "Vehalayla afel umenukar", en: "And the night is dark and estranged," },
      { he: "אתה שם בכל אלה, דואג מלמעלה", tr: "Ata sham bechol ele, do'eg milemala", en: "You are there in all these moments, caring from above," },
      { he: "שלא יהיה לנו קר", tr: "Shelo yihyeh lanu kar", en: "That we won't be chilly." },
      { he: "", tr: "", en: "" },
      { he: "ובינינו נמצא הים", tr: "Uveineinu nimtza hayam", en: "And between us there is an entire ocean;" },
      { he: "השמיים ואולי העולם", tr: "Hashamayim ve'ulai ha'olam", en: "the sky, and maybe the whole world." },
      { he: "וגם הם לא יפרידו בינינו, ילדי הקטן", tr: "Vegam hem lo yafridu beineinu, yaldi hakatan", en: "And they, too, won't separate us, my little child." },
      { he: "ואפשר לנסות ולחייך, לאהוב וללכת קדימה", tr: "Ve'efshar lenasot ulechayech, le'ehov velelechet kadima", en: "And we can try to smile, to love and to continue on forward," },
      { he: "ובסוף ניפגש ונשוב להיות", tr: "Uvasof nipagesh venashuv lihiyot", en: "And in the end we will all meet, and, once more, be–" },
      { he: "ילד ואבא ואמא", tr: "Yeled ve'abba ve'imma", en: "A child, and a father, and a mother." },
      { he: "", tr: "", en: "" },
      { he: "בכל פעם שיש יום הולדת", tr: "Bechol pa'am sheyesh yom huledet", en: "Every time there is a birthday," },
      { he: "ולבית באים חברים", tr: "Velabayit ba'im chaverim", en: "And friends come over to our home," },
      { he: "אתה שם בכל אלה, משגיח למעלה", tr: "Ata sham bechol ele, mashgi'ach lemala", en: "You are there in all these moments, watching from above," },
      { he: "שרק יהיה פה טעים", tr: "Sherak yihyeh po ta'im", en: "That it will all be delicious." },
      { he: "", tr: "", en: "" },
      { he: "וכשבכי תינוק מפציע", tr: "Uchshebechi tinok maftzi'a", en: "And when the cry of a baby erupts," },
      { he: "זה דוקר ושורף את הלב", tr: "Ze doker vesoref et halev", en: "It pierces and burns the heart," },
      { he: "אתה שם בכל אלה, שומר מלמעלה", tr: "Ata sham bechol ele, shomer milemala", en: "You are there in all these moments, protecting from above," },
      { he: "שלא יהיה לי כואב", tr: "Shelo yihyeh li ko'ev", en: "That I won't be in pain." },
      { he: "", tr: "", en: "" },
      { he: "ובינינו נמצא הים", tr: "Uveineinu nimtza hayam", en: "And between us there is an entire ocean;" },
      { he: "השמיים ואולי העולם", tr: "Hashamayim ve'ulai ha'olam", en: "the sky, and maybe the whole world." },
      { he: "וגם הם לא יפרידו בינינו, ילדי הקטן", tr: "Vegam hem lo yafridu beineinu, yaldi hakatan", en: "And they, too, won't separate us, my little child." },
      { he: "ואפשר לנסות ולחייך, לאהוב וללכת קדימה", tr: "Ve'efshar lenasot ulechayech, le'ehov velelechet kadima", en: "And we can try to smile, to love and to continue on forward," },
      { he: "ובסוף ניפגש ונשוב להיות", tr: "Uvasof nipagesh venashuv lihiyot", en: "And in the end we will all meet, and, once more, be–" },
      { he: "ילד, אבא ואמא.", tr: "Yeled, abba ve'imma.", en: "A child, father, and a mother." }
    ]
  },
  {
    id: 9,
    title: "Good Night, Sean",
    titleHebrew: "לילה טוב, שון",
    artist: "Hanan Ben Ari",
    videoUrl: "MXdmcsnsL_A",
    credits: "Written and composed by Hanan Ben-Ari, adapted from the farewell letters of Sgt. Sean Mondschein. Translated by Naama Ben-Dor.",
    context: "Sergeant Sean Mondschein, a soldier in the Golani Brigade, was born on December 30th, 1994, to Menachem and Ninet Mondschein. In June 2014, the Israel Defense Forces launched Operation Protective Edge after Hamas terrorists kidnapped and murdered three Israeli teenagers. On July 20, 2014, Sean was called to Gaza for an operation in the Shuja'iya neighborhood where he, along with six of his crew members, were killed when their APC was hit by an enemy missile. A few days before entering Gaza, he wrote farewell letters to his family and friends on his phone, in case he wouldn't return from battle. In 2018, the Israeli artist Hanan Ben-Ari adapted these letters to write and compose \"Good Night, Sean,\" as part of the \"Creation of My Life\" memorial project.",
    lyrics: [
      { he: "אמא", tr: "Imma", en: "Mom" },
      { he: "אני אוהב אותך באמת!", tr: "Ani ohev otach be'emet!", en: "I love you—truly!" },
      { he: "היית האמא הכי מדהימה בעולם", tr: "Hayit ha'imma hachi madhima ba'olam", en: "You were the most amazing mom in the world" },
      { he: "יותר ממה שאפשר לבקש", tr: "Yoter mima she'efshar levakesh", en: "Better than anything one could asked for" },
      { he: "לא רציתי להדאיג אותך", tr: "Lo ratziti lehad'ig otach", en: "I didn't want to worry you" },
      { he: "מהכניסה לעזה או משהו", tr: "Mehakhnisa le'Aza o mashehu", en: "About our entry into Gaza, or anything" },
      { he: "בבקשה תהיי חזקה בשבילי", tr: "Bevakasha tihiyi chazaka bishvili", en: "Please be strong for me" },
      { he: "ואם יקרה לי משהו תחייכי בגאווה", tr: "Ve'im yikreh li mashehu techaychi bega'ava", en: "And if anything happens to me, smile with pride" },
      { he: "אני אוהב אותך", tr: "Ani ohev otach", en: "I love you" },
      { he: "אוהב אותך", tr: "Ohev otach", en: "love you" },
      { he: "אוהב אותך", tr: "Ohev otach", en: "love you" },
      { he: "", tr: "", en: "" },
      { he: "אבא", tr: "Abba", en: "Dad" },
      { he: "היית אבא נפלא באמת!", tr: "Hayita abba nifla be'emet!", en: "You were a wonderful dad–truly!" },
      { he: "אבא גבר גבר", tr: "Abba gever gever", en: "A 'man's-man' kind of dad." },
      { he: "למרות שרבנו בחודש האחרון", tr: "Lamrot sheravnu bachodesh ha'acharon", en: "Even though we've been fighting this past month…" },
      { he: "אל תייחס לזה משמעות", tr: "Al teyaches lezeh mashma'ut", en: "Don't give it any thought." },
      { he: "אני אוהב אותך", tr: "Ani ohev otcha", en: "I love you" },
      { he: "אוהב אותך", tr: "Ohev otcha", en: "love you" },
      { he: "אוהב אותך", tr: "Ohev otcha", en: "love you" },
      { he: "אהבת אמת", tr: "Ahavat emet", en: "True love" },
      { he: "", tr: "", en: "" },
      { he: "שחף, שירלי", tr: "Shachaf, Shirli", en: "Shachaf, Shirley" },
      { he: "ולכל הקרובים והחברים", tr: "Ulechol hakrovim vehachaverim", en: "And all of the relatives and friends," },
      { he: "אני אוהב אתכם!", tr: "Ani ohev etchem!", en: "I love you!" },
      { he: "אני אתגעגע אליכם", tr: "Ani etga'age'a aleichem", en: "I will miss you" },
      { he: "ומקווה שלא תתגעגעו אליי", tr: "Umekaveh shelo titga'ag'u elai", en: "And I hope that you won't miss me—" },
      { he: "כי אני שמח", tr: "Ki ani same'ach", en: "Because I'm happy" },
      { he: "שנפלה בחלקי הזכות", tr: "Shenafla bechelki hazchut", en: "to have had the privilege" },
      { he: "ליפול למען המדינה שלי", tr: "Lipol lema'an hamedina sheli", en: "To fall in the service of my country" },
      { he: "אני אוהב אותה", tr: "Ani ohev ota", en: "I love her" },
      { he: "אוהב אותה", tr: "Ohev ota", en: "Love her" },
      { he: "אוהב אותה", tr: "Ohev ota", en: "Love her" },
      { he: "", tr: "", en: "" },
      { he: "אז אם אתם קוראים את המכתבים", tr: "Az im atem kor'im et hamichtavim", en: "So if you're reading these letters" },
      { he: "כנראה שהלכתי לישון...", tr: "Kanir'eh shehalachti lishon...", en: "It looks like I've gone to sleep..." },
      { he: "לילה טוב", tr: "Layla tov", en: "Good night" },
      { he: "שון.", tr: "Sean.", en: "Sean." }
    ]
  },
  {
    id: 10,
    title: "Fathers and Sons",
    titleHebrew: "אבות ובנים",
    artist: "Eviatar Banai",
    videoUrl: "3xEbBuAYbl8",
    credits: "Written and composed by Eviatar Banai (1997). Translated by Naama Ben-Dor.",
    context: "A powerful reflection on the cyclical nature of loss in Israeli society, where fathers bury sons and sons bury fathers. The song captures the universal pain of loss while speaking specifically to the Israeli experience of ongoing conflict.",
    lyrics: [
      { he: "תיכף אני ארצה שתלכו מפה,", tr: "Techef ani ertze shetelchu mipo,", en: "In a moment I'll want you all to leave," },
      { he: "שאוכל כבר ליפול בשקט.", tr: "She'uchal kvar lipol besheket.", en: "So that, finally, I can fall in silence." },
      { he: "שלא תראו את הפצעים נפערים—", tr: "Shelo tir'u et haptza'im nif'arim—", en: "So you won't see the gaping wounds—" },
      { he: "שנשאר לבד ונשבר לאט,", tr: "Shenisha'er levad venishaver le'at,", en: "So we can stay alone, and break apart slowly." },
      { he: "", tr: "", en: "" },
      { he: "תוותרו כבר ותלכו מפה,", tr: "Tevatru kvar vetelchu mipo,", en: "Give up already and leave this place," },
      { he: "שאוכל כבר לצעוק בשקט.", tr: "She'uchal kvar litz'ok besheket.", en: "So that, finally, I can scream in silence." },
      { he: "בלי המבט הקרוע שלכם—", tr: "Bli hamabat hakarua shelachem—", en: "Without your piercing gaze—" },
      { he: "שנשאר לבד, ונשבר לאט.", tr: "Shenisha'er levad, venishaver le'at.", en: "So we can stay alone, and break apart slowly." },
      { he: "", tr: "", en: "" },
      { he: "אבות ובנים סבתות ונכדים,", tr: "Avot uvanim savtot u'nechadim,", en: "Fathers and sons, grandmothers and grandchildren," },
      { he: "הלב של אמא מתפוצץ;", tr: "Halev shel imma mitpotzetz;", en: "Mother's heart is exploding;" },
      { he: "מי אשם לה מי אשם לי?", tr: "Mi ashem la mi ashem li?", en: "Who is to blame for her? Who is to blame for me?" },
      { he: "מי יפרד ממי?", tr: "Mi yipared mimi?", en: "Who will part from whom?" },
      { he: "אבא בוכה על בן בוכה על אבא.", tr: "Abba boche al ben boche al abba.", en: "A father weeps for a son—weeps for a father." },
      { he: "", tr: "", en: "" },
      { he: "תיכף אני ארצה שתלכו מפה.", tr: "Techef ani ertze shetelchu mipo.", en: "In a moment I'll want you all to leave this place ." },
      { he: "לא אפחד ליפול; לא אפחד לגדול.", tr: "Lo efached lipol; lo efached ligdol.", en: "I won't be scared to fall; I won't be scared to grow." },
      { he: "לטבוע או לשוט—", tr: "Litbo'a o lashut—", en: "To sink or to swim—" },
      { he: " לחיות או למות.", tr: "Lichyot o lamut.", en: "To live or to die." },
      { he: "", tr: "", en: "" },
      { he: "אבות ובנים, סבתות ונכדים,", tr: "Avot uvanim, savtot u'nechadim,", en: "Fathers and sons, grandmothers and grandchildren," },
      { he: "הלב של אמא מתפוצץ;", tr: "Halev shel imma mitpotzetz;", en: "Mother's heart is exploding;" },
      { he: "מי אשם לה? מי אשם לי?", tr: "Mi ashem la? Mi ashem li?", en: "Who is to blame for her? Who is to blame for me?" },
      { he: "מי יקבור את מי?", tr: "Mi yikbor et mi?", en: "Who will bury whom?" },
      { he: "אבא בוכה על בן, בוכה על אבא.", tr: "Abba boche al ben, boche al abba.", en: "A father weeps for a son; weeps for a father." },
      { he: "אבא בוכה על בן, בוכה על אבא.", tr: "Abba boche al ben, boche al abba.", en: "A father weeps for a son; weeps for a father." }
    ]
  },
  {
    id: 11,
    title: "Song With No Name",
    titleHebrew: "שיר ללא שם",
    artist: "Yehudit Ravitz",
    videoUrl: "TZbI4874BAg",
    credits: "Written and composed by Shalom Chanoch. Performed by Yehudit Ravitz in 1980.",
    context: "A deeply personal song about longing, connection, and the power of music to bridge distances. The song speaks to the universal experience of yearning for someone distant, while maintaining hope for reunion.",
    lyrics: [
      { he: "כי שירי הוא בת קול ברוח", tr: "Ki shiri hu bat kol baruach", en: "For my song is an echo in the wind," },
      { he: "מכתבי השלוח", tr: "Michtavi hashaluach", en: "My sent letter," },
      { he: "מסילת חיי", tr: "Mesilat chayay", en: "The railway of my life," },
      { he: "געגועי", tr: "Ga'aguay", en: "My longings," },
      { he: "הד תפילותי.", tr: "Hed tfilotay.", en: "The reverberation of my prayers." },
      { he: "", tr: "", en: "" },
      { he: "כי שירי הוא עלה ברוח", tr: "Ki shiri hu aleh baruach", en: "For my song is a leaf in the wind," },
      { he: "הנידף, השכוח", tr: "Hanidaf, hashachu'ach", en: "Scattered, forgotten," },
      { he: "הוא האור הרך הנפקח", tr: "Hu ha'or harach hanifkach", en: "It is the soft light that peeks" },
      { he: "בלילותי", tr: "Beleilotai", en: "Into my nights," },
      { he: "הוא אתה ההולך אלי.", tr: "Hu ata haholech elai.", en: "It is you, coming to me." },
      { he: "", tr: "", en: "" },
      { he: "בנדודי חולפות עלי", tr: "Bin'dudai cholfot alai", en: "In my wanderings, passing me by," },
      { he: "תמונות ונשמות", tr: "Tmunot uneshamot", en: "Are pictures and souls," },
      { he: "ושמות שמות", tr: "Ushemot shemot", en: "And names, names;" },
      { he: "אתה בא והולך אלי.", tr: "Ata ba veholech elai.", en: "You are on your way, coming toward me." },
      { he: "", tr: "", en: "" },
      { he: "איי", tr: "Ay", en: "Oh," },
      { he: "עלטה סביב", tr: "Alata saviv", en: "Darkness surrounds." },
      { he: "הלוואי שאתה מקשיב", tr: "Halevai she'ata makshiv", en: "I hope you are listening," },
      { he: "אולי, אולי, אולי", tr: "Ulai, ulai, ulai", en: "Maybe, maybe, maybe—" },
      { he: "אתה בא והולך אלי.", tr: "Ata ba veholech elai.", en: "You are on your way, and coming to me." },
      { he: "", tr: "", en: "" },
      { he: "בדרכי הולכים איתי", tr: "Bedarchi holchim iti", en: "On my way, going with me," },
      { he: "נופים וניגונים", tr: "Nofim u'nigunim", en: "Are landscapes, and melodies," },
      { he: "ופנים, פנים", tr: "Ufanim, panim", en: "And faces, faces;" },
      { he: "אתה בא והולך אלי.", tr: "Ata ba veholech elai.", en: "You are on your way, and coming to me." },
      { he: "", tr: "", en: "" },
      { he: "יה", tr: "Ya", en: "Oh," },
      { he: "דומיה סביב", tr: "umiya saviv", en: "Silence surrounds." },
      { he: "והיה אם אתה מקשיב", tr: "Vehaya im ata makshiv", en: "And if only you were listening," },
      { he: "אולי, אולי, אולי", tr: "Ulai, ulai, ulai", en: "Maybe, maybe, maybe," },
      { he: "אתה בא והולך אלי", tr: "Ata ba veholech elai", en: "You'd come and go to me." },
      { he: "אולי, אולי, אולי", tr: "Ulai, ulai, ulai", en: "Maybe, maybe, maybe," },
      { he: "אתה בא והולך אלי.", tr: "Ata ba veholech elai.", en: "You'd come and go to me." },
      { he: "", tr: "", en: "" },
      { he: "כי שירי הוא משב הרוח", tr: "Ki shiri hu mashav haruach", en: "For my song is a gust of wind," },
      { he: "חלוני הפתוח", tr: "Chaloni hapatuach", en: "My open window," },
      { he: "מעין כוחי, צחוק ובכי", tr: "Ma'ayan kochi, tzchok uvechi", en: "The wellspring of my power," },
      { he: "Laughter and tears,", tr: "", en: "Laughter and tears," },
      { he: "קץ ייסורי", tr: "Ketz yisurai", en: "The end of my suffering." },
      { he: "אתה בא והולך אלי.", tr: "Ata ba veholech elai.", en: "You are on your way, coming toward me." }
    ]
  },
  {
    id: 12,
    title: "Cyclamen Between the Rocks",
    titleHebrew: "רקפות בין הסלעים",
    artist: "Ariel Horowitz",
    videoUrl: "Svu0QOSz73c",
    credits: "Written and composed by Ariel Horowitz. Translated by Naama Ben-Dor.",
    context: "This song beautifully captures the resilience of the Israeli spirit - like cyclamen flowers that bloom between rocks, the beautiful faces of the nation emerge when needed most, especially in times of crisis and war.",
    lyrics: [
      { he: "בין הצפירות בכביש לרחובות המלוכלכים", tr: "Bein hatzfirot bakvish larechovot hameluchlachim", en: "Between the sirens on the highway to the dirty streets" },
      { he: "בין משפחות הפשע לטלוויזיה השטחית", tr: "Bein mishpachot hapesha latelevizya hashit'chit", en: "Between the crime families and the shallow television" },
      { he: "כמו רקפות בין הסלעים", tr: "Kmo rakafot bein hasla'im", en: "Like cyclamen between the rocks" },
      { he: "הפנים היפים של הארץ מתחבאים", tr: "Hapanim hayafim shel ha'aretz mitchab'im", en: "The beautiful faces of the country are hiding" },
      { he: "", tr: "", en: "" },
      { he: "בין הישנים ברחוב לדקירות במועדון", tr: "Bein hayeshenim barechov ladkirot bamoadon", en: "Between the homeless in the street to the stabbings in the club" },
      { he: "בין מה שבדרך כלל קוראים בעיתון", tr: "Bein ma shebaderech klal kor'im ba'iton", en: "Between what you usually read in the newspaper" },
      { he: "כמו רקפות בין הסלעים", tr: "Kmo rakafot bein hasla'im", en: "Like cyclamen between the rocks" },
      { he: "הפנים היפים של הארץ מתחבאים", tr: "Hapanim hayafim shel ha'aretz mitchab'im", en: "The beautiful faces of the country are hiding" },
      { he: "", tr: "", en: "" },
      { he: "וכשהיא לפתע צריכה", tr: "Uchshehi lefeta tzricha", en: "And when she suddenly needs" },
      { he: "שמישהו יישכב בבוץ בתוך שוכה", tr: "Shemishehu yishkav babotz betoch shucha", en: "Someone to lie down in the mud in a trench" },
      { he: "לא תאמין איך הם מופיעים", tr: "Lo ta'amin eich hem mofi'im", en: "You won't believe how they appear" },
      { he: "כמו רקפות בין הסלעים", tr: "Kmo rakafot bein hasla'im", en: "Like cyclamen between the rocks" },
      { he: "", tr: "", en: "" },
      { he: "בין הדגלים הכתומים לחולצה הכחולה", tr: "Bein hadgalim haketumim lachultza hakchula", en: "Between the orange flags and the blue shirt" },
      { he: "בין שוק הפשפשים לקריית הממשלה", tr: "Bein shuk hapishpeshim lekiryat hamemshala", en: "Between the flea market and the government quarter" },
      { he: "כמו רקפות בין הסלעים", tr: "Kmo rakafot bein hasla'im", en: "Like cyclamen between the rocks" },
      { he: "הפנים היפים של הארץ מתחבאים", tr: "Hapanim hayafim shel ha'aretz mitchab'im", en: "The beautiful faces of the country are hiding" },
      { he: "", tr: "", en: "" },
      { he: "וכשהיא לפתע צריכה", tr: "Uchshehi lefeta tzricha", en: "And when she suddenly needs" },
      { he: "שמישהו יישכב בבוץ בתוך שוכה", tr: "Shemishehu yishkav babotz betoch shucha", en: "Someone to lie down in the mud in a trench" },
      { he: "לא תאמין איך הם מופיעים", tr: "Lo ta'amin eich hem mofi'im", en: "You won't believe how they appear" },
      { he: "כמו רקפות בין הסלעים", tr: "Kmo rakafot bein hasla'im", en: "Like cyclamen between the rocks" },
      { he: "", tr: "", en: "" },
      { he: "בין מגדלי הפאר למרכז הקליטה", tr: "Bein migdalei hape'er lemerkaz haklita", en: "Between the luxury towers and the absorption center" },
      { he: "בין פועלים זרים בשדות החיטה", tr: "Bein po'alim zarim bisdot hachita", en: "Between foreign workers in the wheat fields" },
      { he: "כמו רקפות בין הסלעים", tr: "Kmo rakafot bein hasla'im", en: "Like cyclamen between the rocks" },
      { he: "הפנים היפים של הארץ מתחבאים", tr: "Hapanim hayafim shel ha'aretz mitchab'im", en: "The beautiful faces of the country are hiding" },
      { he: "", tr: "", en: "" },
      { he: "וכשהיא לפתע צריכה", tr: "Uchshehi lefeta tzricha", en: "And when she suddenly needs" },
      { he: "שמישהו יישכב בבוץ בתוך שוכה", tr: "Shemishehu yishkav babotz betoch shucha", en: "Someone to lie down in the mud in a trench" },
      { he: "לא תאמין איך הם מופיעים", tr: "Lo ta'amin eich hem mofi'im", en: "You won't believe how they appear" }
    ]
  },
  {
    id: 13,
    title: "Nothing Will Hurt Me",
    titleHebrew: "שום דבר לא יפגע בי",
    artist: "Knesiyat HaSechel",
    videoUrl: "WN6JM5meZfU",
    credits: "Written and performed by Knesiyat HaSechel. Translated by Naama Ben-Dor.",
    context: "A haunting song about a soldier's promise to his family that nothing will hurt him - not a bullet, not danger. The tragic irony of the song lies in the final lines, where if the family is hearing these words, it means the promise could not be kept.",
    lyrics: [
      { he: "שום דבר לא יפגע בי, שום דבר", tr: "Shum davar lo yifga bi, shum davar", en: "Nothing will hurt me, nothing" },
      { he: "לא אישה לא כדור מחבלים, שום דבר", tr: "Lo isha lo kadur mechablim, shum davar", en: "Not a woman, not a bullet from terrorists, nothing" },
      { he: "כי ככה נשבעתי לאחי, אחותי, להורים", tr: "Ki kacha nishba'ti le'achi, achoti, lahorim", en: "Because that's what I swore to my brother, my sister, my parents" },
      { he: "ובכיתי בלילות ודאגתי בימים", tr: "Uvachiti balaylot ved'agti bayamim", en: "And I cried at night and worried during the day" },
      { he: "כי פחדתי שמשהו יפגע בהורים", tr: "Ki pachadti shemashehu yifga bahorim", en: "Because I was afraid that something would hurt my parents" },
      { he: "וקולו של אבי מהדהד לי בראש כבר שנים", tr: "Vekolo shel avi mehadehed li barosh kvar shanim", en: "And my father's voice has been echoing in my head for years" },
      { he: "", tr: "", en: "" },
      { he: "אם יקרה לך משהו", tr: "Im yikreh lach mashehu", en: "If something happens to you" },
      { he: "אין לי טעם לחיים", tr: "Ein li ta'am lachayim", en: "I have no reason to live" },
      { he: "אין לי טעם למחר", tr: "Ein li ta'am lamachar", en: "I have no reason for tomorrow" },
      { he: "אין לי טעם לחיים", tr: "Ein li ta'am lachayim", en: "I have no reason to live" },
      { he: "אין לי טעם למחר", tr: "Ein li ta'am lamachar", en: "I have no reason for tomorrow" },
      { he: "", tr: "", en: "" },
      { he: "אם אתם עומדים כאן מעלי", tr: "Im atem omdim kan me'alai", en: "If you are standing here above me" },
      { he: "כנראה שלא עמדתי בהבטחתי", tr: "Kanir'eh shelo amadeti behavtachati", en: "It seems I didn't keep my promise" },
      { he: "מצטער, בחיי", tr: "Mitzta'er, bechayay", en: "I'm sorry, I swear" },
      { he: "מצטער, בחיי", tr: "Mitzta'er, bechayay", en: "I'm sorry, I swear" },
      { he: "מצטער, בחיי", tr: "Mitzta'er, bechayay", en: "I'm sorry, I swear" },
      { he: "", tr: "", en: "" },
      { he: "אם יקרה לך משהו...", tr: "Im yikreh lach mashehu...", en: "If something happens to you..." },
      { he: "", tr: "", en: "" },
      { he: "שום דבר לא יפגע בי", tr: "Shum davar lo yifga bi", en: "Nothing will hurt me" },
      { he: "שום דבר", tr: "Shum davar", en: "Nothing" },
      { he: "לא אישה לא כדור מחבלים", tr: "Lo isha lo kadur mechablim", en: "Not a woman, not a bullet from terrorists" },
      { he: "שום דבר", tr: "Shum davar", en: "Nothing" }
    ]
  }
];

// Make songs available globally for the React app
window.songs = songs;

// Export for potential module usage
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { songs };
}