// Songs data for The Zikaron Project
// Refactored to interleave Hebrew and English lines for easier reading.

const songs = [
  {
    id: 1,
    title: "We'll Meet in Dreams",
    titleHebrew: "ניפגש בחלומות",
    artist: "Ilai Botner and Yaldei Hachutz",
    videoUrl: "4J7bQpp_MGo",
    credits: "Written by Noam Chorev, Composed by Ilai Botner, Performed by Ilai Botner and Yaldei Hachutz, Translated (and adapted) by Naama Ben-Dor.",
    context: "This video is part of my project to share English translations of Hebrew remembrance songs with the global community, in an effort to connect Jews throughout the diaspora in their shared pain and experiences.",
    lyrics: [
      { he: "עוד נחזור להיפגש, להסתכל שוב בעיניים.", en: "And we'll meet once again, gaze into each other's eyes." },
      { he: "יש פקק תפילות כבד בנתיב של השמיים.", en: "There's a traffic jam of prayers—on the road to the skies." },
      { he: "אבל החוט הדק בינינו אף פעם לא נקרע.", en: "But the thin thread connecting us will never tear apart." },
      { he: "עוד נצחק שם על הכל, לא תהיה לנו ברירה.", en: "We'll laugh about it all someday, it's the only choice we have." },
      { he: "", en: "" },
      { he: "עוד נצא שוב לטייל בבוקר של שבת,", en: "And once again we'll go outside, go for walks on Shabbat mornings," },
      { he: "נחזיר את השיגרה האבודה לאט לאט.", en: "Restore the old routine that we've lost—slowly, slowly." },
      { he: "נקום מהספה, ננשום את האוויר.", en: "We'll get up off the couch, and breathe in the air." },
      { he: "למדנו עם הזמן שהכל כל כך שביר.", en: "We've learned, with time, how easily—everything can break." },
      { he: "", en: "" },
      { he: "ובינתיים ניפגש בחלומות—", en: "And for now, we will meet in our dreams—" },
      { he: "אני איתך בכל שעה, בכל הנשימות;", en: "I'm with you in every hour, in the air you breathe;" },
      { he: "ואם אתה עמוק מתחת לשמיכה;", en: "And if you're underneath the covers, off to sleep;" },
      { he: "תשאיר לי את הדלת חצי פתוחה.", en: "Leave the door half-open; just for me." },
      { he: "", en: "" },
      { he: "אני שולחת ידיים ארוכות;", en: "I am sending myself forth with open arms;" },
      { he: "הן מחבקות אותך עכשיו, הן מחבקות.", en: "They're wrapped around you now—they hug and guard." },
      { he: "ורק תזכור, שניה, לפני שאתה נרדם,", en: "And just before you fall asleep, lying curled," },
      { he: "שגעגוע הוא הדבק הכי חזק בעולם.", en: "Remember longing is the strongest glue in the world." },
      { he: "", en: "" },
      { he: "עוד נחזור שוב לשחק, להתפרק בחיבוק,", en: "One day we'll play again, and part with an embrace," },
      { he: "השניה הכי קשה היא אחרי הניתוק,", en: "And wince in pain the moment we are split apart by space," },
      { he: "ושער הדמעות שלי נפתח שוב לרווחה,", en: "The floodgates of my tears open quickly, vast and wide," },
      { he: "כי יש עוגה, ויש נרות, אבל אין לי כאן אותך;", en: "'Cause there's cake, and there are candles, but you're not here by my side;" },
      { he: "", en: "" },
      { he: "עוד נחזור להיפגש, נשכב סתם על הגב,", en: "We'll meet again someday, lie casually on our backs," },
      { he: "לא ניקח שום דבר כמובן מאליו.", en: "And never take for granted anything we'll ever have." },
      { he: "וגם אם קצת נרגיש שעברו מיליון שנה,", en: "And even if we'll feel as though a million years have passed," },
      { he: "נמשיך, כאילו כלום, כאילו כלום לא השתנה.", en: "We'll continue, as if nothing— as if nothing changed at all." },
      { he: "", en: "" },
      { he: "ובינתיים ניפגש בחלומות—", en: "And for now, we will meet in our dreams—" },
      { he: "אני איתך בכל שעה, בכל הנשימות;", en: "I'm with you in every hour, in the air you breathe;" },
      { he: "ואם אתה עמוק מתחת לשמיכה;", en: "And if you're underneath the covers, off to sleep;" },
      { he: "תשאיר לי את הדלת חצי פתוחה.", en: "Leave the door half-open; just for me." },
      { he: "", en: "" },
      { he: "אני שולחת ידיים ארוכות;", en: "I am sending myself forth with open arms;" },
      { he: "הן מחבקות אותך עכשיו, הן מחבקות.", en: "They're wrapped around you now—they hug and guard." },
      { he: "ורק תזכור שניה לפני שאתה נרדם,", en: "And just before you fall asleep, lying curled," },
      { he: "שגעגוע הוא הדבק הכי חזק בעולם.", en: "Remember longing is the strongest glue in the world." },
      { he: "", en: "" },
      { he: "אני שולחת ידיים ארוכות;", en: "I am sending myself forth with open arms;" },
      { he: "הן מחבקות אותך עכשיו, הן מחבקות.", en: "They're wrapped around you now—they hug and guard." },
      { he: "ורק תזכור שניה לפני שאתה נרדם,", en: "And just before you fall asleep, lying curled," },
      { he: "", en: "" },
      { he: "שגעגוע הוא הדבק הכי חזק בעולם.", en: "Remember longing is the strongest glue in the world." },
      { he: "שגעגוע הוא הדבק הכי חזק בעולם.", en: "Remember longing is the strongest glue in the world." },
      { he: "שגעגוע הוא הדבק הכי חזק בעולם.", en: "Remember longing is the strongest glue in the world." }
    ]
  },
  {
    id: 2,
    title: "Medic's Ballad",
    titleHebrew: "בלדה לחובש",
    artist: "Yehoram Gaon",
    videoUrl: "86wdOmnW0yo",
    credits: "Written by Dan Almagor in 1956, Composed by Effie Netzer in 1968, Performed by Yehoram Gaon in 1969, Translated and Edited by Naama Ben-Dor.",
    context: "This video is part of my project to share English translations of Hebrew remembrance songs with the global community, in an effort to connect Jews throughout the diaspora in their shared pain and experiences. \"Medic's Ballad\" conveys the bravery, heroism, and self-sacrifice exemplified by so many of our fallen soldiers. It also highlights the camaraderie and unbreakable bonds that unite Israeli society, and that make each loss all the more tragic.",
    lyrics: [
      { he: "הם התקדמו לאט. הכל היה רגוע;", en: "They proceeded onward slowly. Everything was calm;" },
      { he: "מנגד הנהר וגומא מרשרש.", en: "The reeds rustled across the river." },
      { he: "פתאום רעם ברק, אחד צעק: \"פצוע!\"", en: "Suddenly thunder and lightning, someone shouted: \"wounded!\"" },
      { he: "\"אני כבר בא\" — ענה לו החובש.", en: "\"I'm already on my way\" — replied the medic." },
      { he: "", en: "" },
      { he: "\"עלינו על מוקש!\" — צעק אז הפצוע,", en: "\"We stepped on a mine!\" — the wounded man shouted then," },
      { he: "\"אני כאן, לצידך\" — ענה לו החובש.", en: "\"I'm right here, by your side.\" — the medic answered him." },
      { he: "ברד של אש ניתך; ברד כבד קטוע,", en: "A hail of fire poured; heavy, fragmented hail," },
      { he: "מעבר לנהר, לגומא הרוחש.", en: "Across the river, where the reeds rustled." },
      { he: "\"השאירו אותי כאן!\" — ביקש אז הפצוע,", en: "\"Leave me here!\" — the wounded man then begged," },
      { he: "\"עזוב שטויות.\" — ענה לו החובש.", en: "\"Stop with the nonsense.\" — the medic replied." },
      { he: "\"תציל את עצמך!\" — ביקש אז הפצוע.", en: "\"Save yourself!\" — the wounded man pleaded." },
      { he: "\"אני נשאר איתך.\" — ענה לו החובש.", en: "\"I'm staying here with you.\" — the medic answered him." },
      { he: "", en: "" },
      { he: "והם נותרו שניהם, והשדה פתוח.", en: "And the two of them remained, and the field was open." },
      { he: "והם נותרו שניהם, והם גלויים לאש.", en: "And the two of them remained, and they were exposed to fire." },
      { he: "", en: "" },
      { he: "\"אנחנו אבודים!\" — מילמל אז הפצוע,", en: "\"We're a lost cause!\" — the wounded man then muttered," },
      { he: "\"אחוז בי טוב.\" — ענה לו החובש.", en: "\"Hold tight onto me.\" — the medic responded." },
      { he: "\"נפצעת גם אתה!\" — מילמל אז הפצוע", en: "\"You were also wounded!\" — the wounded man then mumbled," },
      { he: "\"עזוב, זה לא נורא.\" — ענה לו החובש.", en: "\"Forget it, it's not serious.\" — the medic answered him." },
      { he: "", en: "" },
      { he: "האש כבדה, כבדה! קשה, קשה לנוע.", en: "The fire is heavy, heavy! It's difficult to move." },
      { he: "רק לא להתייאש, רק לא להתייאש,", en: "Just don't give up, just don't give up!" },
      { he: "", en: "" },
      { he: "\"אזכור אותך תמיד.\" — נשבע אז הפצוע.", en: "\"I'll remember you forever.\" — the wounded man then swore." },
      { he: "\"רק לא ליפול.\" — מילמל אז החובש.", en: "\"Just don't fall\" — the medic muttered then." },
      { he: "\"שלך עד יום מותך!\"— נשבע אז הפצוע.", en: "\"I'm yours until you die\" — the wounded man then swore." },
      { he: "\"היום הוא יום מותי.\" — ענה לו החובש.", en: "\"Today's my day of death\" — the medic answered him." },
      { he: "", en: "" },
      { he: "פתאום ענן אבק, פתאום עלתה הרוח,", en: "Suddenly, a cloud of dust, suddenly the wind swept up," },
      { he: "וצל על הקרקע, והוא קרב, רועש.", en: "And a shadow on the ground, and it approached, loudly." },
      { he: "\"ניצלנו! הם באים!\" — ייבב אז הפצוע;", en: "\"We're rescued! They're coming!\" — the wounded man then shrieked;" },
      { he: "אך לא שמע מילה מן החובש.", en: "But he didn't hear a word from the medic." },
      { he: "", en: "" },
      { he: "\"אחי, אחי שלי!\" — ייבב אז הפצוע.", en: "\"My brother, my brother!\" — the wounded man then wailed." },
      { he: "מעבר לנהר הגומא מרשרש.", en: "Across the river, the reeds rustled." },
      { he: "", en: "" },
      { he: "\"אחי, אחי שלי—\"", en: "\"My brother, my brother\" —" },
      { he: "\"אחי, אחי שלי—\"", en: "\"My brother, my brother\" —" },
      { he: "\"אחי!\"", en: "\"My brother!\"" }
    ]
  },
  {
    id: 3,
    title: "Where Are You",
    titleHebrew: "אייכה",
    artist: "Shuli Rand",
    videoUrl: "SbYYJA1gFkk",
    credits: "Written and performed by Shuli Rand in 2008. Translated and Edited by Naama Ben-Dor. The images generated for this video were created using Gemini AI.",
    context: "This video is part of my project to share English translations of Hebrew remembrance songs with the global community, in an effort to connect Jews throughout the diaspora in their shared pain and experiences. \"אייכה\" symbolizes the agonizing clash between faith and misery, and is sometimes performed at Holocaust Remembrance Day ceremonies and other memorial events.",
    lyrics: [
      { he: "ריבונו של עולם, אם נדבר גלויות,", en: "Master of the universe, if we're speaking frankly," },
      { he: "לפעמים אין לי כוח בעולמך להיות.", en: "Sometimes I lack the strength to remain in your world." },
      { he: "אנה מפניך אסתתר?", en: "Where could I conceal myself from your gaze?" },
      { he: "מה אטען?", en: "What would I claim?" },
      { he: "מה אצטדק?", en: "How would I justify myself?" },
      { he: "מה אדבר?", en: "What would I say?" },
      { he: "", en: "" },
      { he: "חנון ורחום, הן לפניך גלוי", en: "Merciful and gracious, indeed all is revealed to You." },
      { he: "כאן יהודי שעל חוט—", en: "Before You is a Jew on a string—" },
      { he: "השערה הוא תלוי.", en: "Hanging by a hair." },
      { he: "נלחם בעצבות;", en: "Wrestling the sadness;" },
      { he: "בייאוש המכרסם—כתולעת.", en: "The despair that gnaws—like a worm." },
      { he: "השמחה נסתלקה ממני—", en: "The joy has been extinguished in me—" },
      { he: "וגם הדעת.", en: "And so has reason." },
      { he: "", en: "" },
      { he: "קולות מהעבר לוחשים לי לעצור,", en: "Voices from the past whisper at me to quit," },
      { he: "אבל אני מוסיף בחושך לחתור,", en: "But I continue to row in the darkness." },
      { he: "ושואל;", en: "And I ask;" },
      { he: "ומבקש;", en: "And I plead;" },
      { he: "איה—", en: "Where—" },
      { he: "איה—", en: "Where—" },
      { he: "או, אייכה?", en: "Where are You?" },
      { he: "", en: "" },
      { he: "איה—", en: "Where—" },
      { he: "איה?", en: "Where?" },
      { he: "או, אייכה?", en: "Where are You?" },
      { he: "אייכה?", en: "Where are You?" },
      { he: "", en: "" },
      { he: "אותו זקן וכסיל שולח בי חיצים,", en: "That same old fool sends arrows out at me." },
      { he: "אני הולך וכושל;", en: "I walk and stumble;" },
      { he: "הוא הולך ומעצים.", en: "He continues and intensifies." },
      { he: "נשמה קדושה אל נא תבכי, שבורת-כנף.", en: "Holy soul do not weep, broken-winged." },
      { he: "הן, תעידי עליי כמה הייתי נכסף.", en: "Indeed, you would attest how greatly I've yearned." },
      { he: "", en: "" },
      { he: "כשסודות מהעבר פקדו עליי לעצור,", en: "When secrets from the past commanded me to quit," },
      { he: "אבל אני מוסיף, בחושך לחתור.", en: "But I continue to row in the darkness." },
      { he: "ושואל;", en: "And I ask;" },
      { he: "ומבקש;", en: "And I plead;" },
      { he: "איה—", en: "Where—" },
      { he: "איה—", en: "Where—" },
      { he: "או, אייכה?", en: "Where are You?" },
      { he: "", en: "" },
      { he: "איה—", en: "Where, where, where are You?" },
      { he: "איה—", en: "Where, where, where are You?" },
      { he: "אייכה?", en: "Where are You?" },
      { he: "אייכה?", en: "Where are You?" },
      { he: "", en: "" },
      { he: "בסופו של יום, הן אפלט אל החוף,", en: "At the end of the day, I will be hurled onto the sand." },
      { he: "האדמה הרחומה אותי אליה תאסוף.", en: "The merciful earth will take me in." },
      { he: "ואז אצעק;", en: "And then I will yell;" },
      { he: "ואצטדק;", en: "And justify myself;" },
      { he: "ואספר—", en: "And recount—" },
      { he: "איך בחושך הזה הייתי חותר,", en: "How I used to row through this darkness," },
      { he: "ושואל, ומבקש, וכוסף...", en: "And ask, and plead, and yearn…" },
      { he: "אייכה?", en: "Where are You?" }
    ]
  },
  {
    id: 4,
    title: "In Our Kindergarten",
    titleHebrew: "אצלנו בגן",
    artist: "Shayli Atari",
    videoUrl: "h7lxLgEQsOw",
    credits: "Written and composed by Yiftach Kerzner in memory of his friend, Tom Farkash, who fell in the Second Lebanon War. The song was performed by Shayli Atari in 2014. Translated by Naama Ben-Dor.",
    context: "Etzlenu BaGan (אצלנו בגן) was written and composed by Yiftach Kerzner in memory of his friend, Tom Farkash, who fell in the Second Lebanon War. The song was performed by Shayli Atari in 2014, during Operation Protective Edge, but has since taken on added significance, as Atari's husband was later murdered on Oct. 7, 2023, while protecting his wife and one-month-old daughter from Hamas terrorists who infiltrated into their home.",
    lyrics: [
      { he: "אצלנו בגן יש המון ילדים", en: "At our kindergarten, there are many kids," },
      { he: "את חלקם אני אוהב", en: "Some of them—I like" },
      { he: "את חלקם אני לא מכיר", en: "Some—I don't know." },
      { he: "אבל מי לא שמע על האומץ של רן", en: "But who hasn't heard of Ran's courage?" },
      { he: "הוא הכי מהיר בחול הוא הכי חזק בגן", en: "He's the fastest in the sand, he's the strongest in the kindergarten" },
      { he: "אבל יש לו סוד אחד שפחד הוא לגלות", en: "But he has this one secret, that he's scared to reveal;" },
      { he: "שהוא כל כך מאוהב באחת הילדות", en: "That he's madly in love with one of the girls." },
      { he: "", en: "" },
      { he: "אז בלילות קרים", en: "So on cold nights," },
      { he: "עם פנס מתחת לשמיכה הם מדברים", en: "With a flashlight under the covers, they talk" },
      { he: "והוא מגלה לה מה היא בשבילו—כל עולמו", en: "And he confesses to her what she means to him—his entire world." },
      { he: "מוגן מתחת לשמיכה", en: "Protected underneath the blanket." },
      { he: "", en: "" },
      { he: "אצלנו בגן יש הרבה חבורות", en: "At our kindergarten there are many cliques" },
      { he: "יש כאלה נחשבים יש כאלה שפחות", en: "Some are considered \"cool,\" others not as much." },
      { he: "אבל מי לא שמע על קופצי הנדנדות", en: "But who hasn't heard of the Swing-Jumpers" },
      { he: "מריעים להם כפיים מלמדים אותם לנחות", en: "They are showered with applause, they are taught how to land" },
      { he: "מורמים על נס הדגל גאוות כל האזור", en: "They are raised up with the flag, the pride of the entire region" },
      { he: "רק לפעמים כשהם קופצים רחוק הם שוכחים לחזור", en: "Except—sometimes when they jump too far, they forget to return." },
      { he: "", en: "" },
      { he: "אז בלילות קרים", en: "So on cold nights" },
      { he: "עם פנס מתחת לשמיכה הם מדברים", en: "With a flashlight under the covers they talk" },
      { he: "והוא מגלה לה מה היא בשבילו—כל עולמו", en: "And he confesses to her what she means to him—his entire world. Protected underneath the blanket." },
      { he: "מוגן מתחת לשמיכה", en: "" },
      { he: "", en: "" },
      { he: "אצלנו בגן נפרדים בשמחה", en: "At our kindergarten, we part with a smile" },
      { he: "כי היום לא ארוך ונפגשים שוב מחר", en: "Because the day isn't long, and we'll meet again tomorrow" },
      { he: "חוץ מאלה שפתאום לא חוזרים יותר לגן", en: "Except for those who suddenly stop returning to the kindergarten" },
      { he: "אמרו לי שהם רק עברו דירה מעבר לענן", en: "I was told that they just moved to a new home, on the other side of the clouds." },
      { he: "", en: "" },
      { he: "אז בלילות קרים", en: "So on cold nights" },
      { he: "עם פנס מתחת לשמיכה הם מדברים", en: "With a flashlight under the covers they talk" },
      { he: "והוא מגלה לה מה היא בשבילו", en: "And he confesses to her what she means to him —" },
      { he: "והיא בוכה שהוא מציע לה להיות—כל עולמו", en: "And she cries when he proposes that she be—his entire world," },
      { he: "בערב שלפני המלחמה.", en: "On the evening before the war." },
      { he: "", en: "" },
      { he: "אצלנו בגדוד, יש המון ילדים", en: "In our battalion, there are many kids," },
      { he: "את חלקם אני אוהב", en: "Some of them—I like" },
      { he: "את חלקם אני לא אכיר", en: "Some—I'll never meet." }
    ]
  },
  {
    id: 5,
    title: "The Wheat Grows Again",
    titleHebrew: "החיטה צומחת שוב",
    artist: "Chava Alberstein",
    videoUrl: "m3p_TnEhyto",
    credits: "Written by Dorit Tzameret in 1974, Melody composed by Haim Barkani in 1978, Performed by Chava Alberstein in 1983, Translated to English by Naama Ben-Dor.",
    context: "The Wheat Still Grows Again was written by Dorit Tzameret in 1974, after eleven members of her kibbutz were killed in the Yom Kippur War. The melody was later composed by Haim Barkani in 1978. This rendition was performed by Chava Alberstein in 1983.",
    lyrics: [
      { he: "שדות שפוכים הרחק", en: "Fields spill out into the distance," },
      { he: "מאופק ועד סף", en: "Until the edge of the horizon" },
      { he: "וחרובים וזית וגלבוע -", en: "And carobs, and olives, and the Gilboa—" },
      { he: "ואל ערבו העמק נאסף", en: "And the valley is engulfed by the evening." },
      { he: "ביופי שעוד לא היה כמוהו.", en: "With beauty that exceeds all that came before." },
      { he: "", en: "" },
      { he: "זה לא אותו העמק, זה לא אותו הבית,", en: "This is not the same valley, this is not the same home" },
      { he: "אתם אינכם ולא תוכלו לשוב", en: "You all are gone, and you can never return" },
      { he: "השביל עם השדרה, ובשמיים עיט", en: "The path with the boulevard, and in the sky–an eagle" },
      { he: "אך החיטה צומחת שוב", en: "And yet, the wheat grows again." },
      { he: "", en: "" },
      { he: "מן העפר המר העיריות עולות", en: "From beneath the bitter ashes, the asphodels bloom" },
      { he: "ועל הדשא ילד וכלבו", en: "And on the grass, a boy and his dog" },
      { he: "מואר החדר ויורדים לילות", en: "The well-lit room radiates as the nights fall" },
      { he: "על מה שבו ומה שבליבו", en: "Over that which lies inside, and within his heart" },
      { he: "", en: "" },
      { he: "זה לא אותו העמק, זה לא אותו הבית,", en: "This is not the same valley, this is not the same home" },
      { he: "אתם אינכם ולא תוכלו לשוב", en: "You all are gone, and you can never return" },
      { he: "השביל עם השדרה, ובשמיים עיט -", en: "The path with the boulevard, and in the sky–an eagle" },
      { he: "אך החיטה צומחת שוב", en: "And yet, the wheat grows again." },
      { he: "", en: "" },
      { he: "וכל מה שהיה אולי יהיה לעד", en: "And everything that was, perhaps will always be" },
      { he: "זרח השמש שוב השמש בא", en: "The sun rose; again, the sun returns" },
      { he: "עוד השירים שרים אך איך יוגד", en: "And still, the songs are sung, but how can they convey" },
      { he: "כל המכאוב וכל האהבה", en: "The depths of the pain, and the depths of the love." },
      { he: "", en: "" },
      { he: "הן זה אותו העמק, הן זה אותו הבית", en: "Yes, this is the same valley, yes, this is the same home" },
      { he: "אבל אתם הן לא תוכלו לשוב", en: "But you—yes, you can never return" },
      { he: "ואיך קרה, ואיך קרה? ואיך קורה עדיין", en: "And how did it happen, and how did it happen? And how can it still be" },
      { he: "שהחיטה צומחת שוב?", en: "That the wheat grows again?" },
      { he: "ואיך קרה, ואיך קרה ואיך קורה עדיין…", en: "And how did it happen, and how did it happen? And how can it still be…" },
      { he: "שהחיטה,", en: "That the wheat," },
      { he: "שהחיטה צומחת שוב.", en: "That the wheat grows again." }
    ]
  },
  {
    id: 6,
    title: "Dance",
    titleHebrew: "תרקדי",
    artist: "Osher Cohen",
    videoUrl: "8_3BYyW2zT0",
    credits: "Lyrics and music: Osher Cohen, Nadav (Navi) Aharoni. Arrangement and musical production: Nadav (Navi) Aharoni. Translated by Naama Ben-Dor.",
    context: "Dance (תרקדי) was written and composed by Osher Cohen and Nadav (Navi) Aharoni in memory of the victims killed on October 7, 2023 at the Nova music festival massacre in Kibbutz Re'im.",
    lyrics: [
      { he: "תרקדי.", en: "Dance." },
      { he: "השירים עושים לך טוב.", en: "The songs will do you good." },
      { he: "כולם חברים כאן,", en: "We are all friends here," },
      { he: "אחים אחיות.", en: "Brothers and sisters." },
      { he: "", en: "" },
      { he: "תרקדי.", en: "Dance." },
      { he: "נו תעופי בלי לחשוב.", en: "Go on and fly, without thinking." },
      { he: "פה ושם תירגעי קצת.", en: "Here and there calm yourself a little." },
      { he: "תשמרי לך כוחות.", en: "Save your strengths." },
      { he: "", en: "" },
      { he: "אולי תברחי… אין לנו זמן.", en: "Maybe you will escape… We don't have time." },
      { he: "אולי תברחי… הם עוד מעט כאן.", en: "Maybe you will escape… They are almost here." },
      { he: "", en: "" },
      { he: "ואם תשמעי—", en: "And If you hear—" },
      { he: "צליפות הדשא,", en: "The whipping of grass," },
      { he: "חוטי עשן,", en: "The strings of smoke," },
      { he: "תרוצי מהר; את נגד הזמן.", en: "Run away quick; time is against you." },
      { he: "", en: "" },
      { he: "שריקות ההדף,", en: "The whistles of the blasts," },
      { he: "עמודי הענן,", en: "The pillars of clouds," },
      { he: "אל תעצרי, אני בדרך,", en: "Don't stop, I am on my way," },
      { he: "ואם עייפת—", en: "And if you've tired out—" },
      { he: "", en: "" },
      { he: "את בטח רוקדת לך שם.", en: "You're probably already up there, dancing." },
      { he: "את בטח רוקדת לך שם.", en: "You're probably already up there, dancing." },
      { he: "", en: "" },
      { he: "תרקדי.", en: "Dance." },
      { he: "אל תדאגי, זה הנוף.", en: "Don't worry, this is the view." },
      { he: "שכלום לא יזיז לך,", en: "Don't let anything stir you," },
      { he: "גם לא אש הקרבות.", en: "Not even the fires of battle." },
      { he: "", en: "" },
      { he: "תרקדי.", en: "Dance." },
      { he: "נתראה בקרוב.", en: "We will meet again soon." },
      { he: "כולם מחכים לך,", en: "Everyone is waiting for you," },
      { he: "רק עוד כמה שבתות.", en: "It'll only be a few more Shabbats." },
      { he: "", en: "" },
      { he: "אל תדאגי,", en: "Don't worry," },
      { he: "ייקח לנו זמן.", en: "It will take us a while." },
      { he: "אל תדאגי,", en: "Don't worry," },
      { he: "את עוד מעט כאן.", en: "You are almost here." },
      { he: "", en: "" },
      { he: "ואם תשמעי—", en: "And If you hear—" },
      { he: "צליפות הדשא,", en: "The whipping of grass," },
      { he: "חוטי עשן,", en: "The strings of smoke," },
      { he: "תרוצי מהר; את נגד הזמן.", en: "Run away quick; time is against you." },
      { he: "", en: "" },
      { he: "שריקות ההדף,", en: "The whistles of the blasts," },
      { he: "עמודי הענן,", en: "The pillars of clouds," },
      { he: "אל תעצרי, אני בדרך,", en: "Don't stop, I am on my way," },
      { he: "ואם עייפת—", en: "And if you've tired out—" },
      { he: "", en: "" },
      { he: "את בטח רוקדת לך שם.", en: "You're probably already up there, dancing." },
      { he: "את בטח רוקדת לך שם.", en: "You're probably already up there, dancing." },
      { he: "את בטח רוקדת לך שם.", en: "You're probably already up there, dancing." },
      { he: "לה לה לה לה לה לה", en: "" },
      { he: "", en: "" },
      { he: "צליפות הדשא,", en: "Whipping of grass," },
      { he: "חוטי העשן,", en: "The strings of smoke," },
      { he: "תרוצי מהר,", en: "Run away quick," },
      { he: "את נגד הזמן.", en: "Time is against you." },
      { he: "", en: "" },
      { he: "שריקות ההדף,", en: "The whistles of the blasts," },
      { he: "עמודי הענן,", en: "The pillars of clouds," },
      { he: "אל תעצרי, אני בדרך,", en: "Don't stop, I am on my way," },
      { he: "ואם עייפת—", en: "And if you've tired out—" },
      { he: "", en: "" },
      { he: "שריטות הנפש,", en: "The wounds to your soul," },
      { he: "עוד יהיו לך מקלט,", en: "Will be your refuge," },
      { he: "אל תעצרי, כי את לוחמת,", en: "Don't stop, because you are a fighter," },
      { he: "ואם עייפת—", en: "And if you've tired yourself out—" },
      { he: "", en: "" },
      { he: "את בטח רוקדת לך שם.", en: "You're probably already up there, dancing." }
    ]
  },
  {
    id: 7,
    title: "Perach (Flower)",
    titleHebrew: "פרח",
    artist: "Yehuda Poliker",
    videoUrl: "icI7Hmrr7YM",
    credits: "Written by Tzruya Lahav and composed by Yehuda Poliker in 1985. Translated by Naama Ben-Dor.",
    context: "\"Perach\" was written by Tzruya Lahav and composed by Yehuda Poliker in 1985, in memory of the victims of the Ras Burqa massacre. On October 5th, 1985, an Egyptian soldier opened fire at a group of Israeli tourists at a beach resort located in the Ras Burqa bay on the Sinai peninsula. He murdered three adults and four young children.",
    lyrics: [
      { he: "שם, בעפר ותכלת,", en: "There, in the dust and sky," },
      { he: "חלקת שלום ישנה.", en: "Lies a grave of peace." },
      { he: "נומי פרח, נומי.", en: "Sleep, flower, sleep." },
      { he: "נומי, ילדה קטנה.", en: "Sleep, little girl." },
      { he: "", en: "" },
      { he: "את החיים—לקחו לך;", en: "Your life—they stole from you;" },
      { he: "הו, מלחמות קדושות.", en: "Oh, holy wars." },
      { he: "מלאכים בכו לך—", en: "Angels wept for you—" },
      { he: "בעיניים יבשות.", en: "With eyes devoid of tears." },
      { he: "", en: "" },
      { he: "את חיוכך, תינוקת;", en: "Your smile, baby girl;" },
      { he: "קברו באדמה,", en: "They buried in the earth." },
      { he: "איך צומח שקט,", en: "How does silence bloom," },
      { he: "מתוך המהומה?", en: "Out of the chaos?" },
      { he: "", en: "" },
      { he: "מי שלחץ על הדק—", en: "He, who pulled the trigger—" },
      { he: "דם, את ליבו מכתים.", en: "Taints his heart with blood." },
      { he: "במלחמות לצדק,", en: "In battles for justice," },
      { he: "גם ילדים מתים.", en: "Even children are killed." },
      { he: "", en: "" },
      { he: "את החיים—לקחו לך;", en: "Your life—they stole from you;" },
      { he: "הו, מלחמות קדושות.", en: "Oh, holy wars." },
      { he: "מלאכים בכו לך—", en: "Angels wept for you—" },
      { he: "בעיניים יבשות.", en: "With dry eyes." },
      { he: "", en: "" },
      { he: "שם, בעפר ותכלת,", en: "There, in the dust and sky," },
      { he: "חלקת שלום ישנה.", en: "A grave of peace lies asleep." },
      { he: "נומי פרח, נומי.", en: "Sleep, flower, sleep." },
      { he: "נומי, ילדה קטנה.", en: "Sleep, little girl." },
      { he: "", en: "" },
      { he: "את החיים—לקחו לך.", en: "Of your life—they robbed you;" },
      { he: "הו, מלחמות קדושות.", en: "Oh, holy wars." },
      { he: "מלאכים בכו לך—", en: "Angels wept for you—" },
      { he: "בעיניים יבשות.", en: "With dry eyes." },
      { he: "", en: "" },
      { he: "וחלומך ברוח,", en: "And your dream in the wind," },
      { he: "חרוז למנגינה.", en: "Rhymes with the melody." },
      { he: "נומי פרח, נומי.", en: "Sleep, flower, sleep." },
      { he: "נומי ילדה קטנה.", en: "Sleep, little girl." }
    ]
  },
  {
    id: 8,
    title: "Child, Father, and Mother",
    titleHebrew: "ילד ואבא ואמא",
    artist: "Harel Skat and Ilai Botner",
    videoUrl: "qNUAYbkew18",
    credits: "Written and composed by Ilai Botner, Performed by Harel Skat and the children of the IDF Widows and Orphans Organization. Translated by Naama Ben-Dor.",
    context: "A touching song about loss and hope, performed by children who have lost parents in service to Israel. The song speaks of the eternal connection between loved ones, separated by distance but never truly apart.",
    lyrics: [
      { he: "בכל פעם כששמש שוקעת", en: "Every time the sun sets" },
      { he: "כשמטוס בשמיים עובר", en: "And a plane passes through the sky" },
      { he: "אתה שם בכל אלה, שומר מלמעלה", en: "You are there—in all these moments, protecting from above" },
      { he: "שכלום לא יהיה כאן חסר", en: "Ensuring that nothing here will be missing." },
      { he: "", en: "" },
      { he: "וכשגשם ראשון מגיע", en: "And when the first rainfall arrives," },
      { he: "והלילה אפל ומנוכר", en: "And the night is dark and estranged," },
      { he: "אתה שם בכל אלה, דואג מלמעלה", en: "You are there in all these moments, caring from above," },
      { he: "שלא יהיה לנו קר", en: "That we won't be chilly." },
      { he: "", en: "" },
      { he: "ובינינו נמצא הים", en: "And between us there is an entire ocean;" },
      { he: "השמיים ואולי העולם", en: "the sky, and maybe the whole world." },
      { he: "וגם הם לא יפרידו בינינו, ילדי הקטן", en: "And they, too, won't separate us, my little child." },
      { he: "ואפשר לנסות ולחייך, לאהוב וללכת קדימה", en: "And we can try to smile, to love and to continue on forward," },
      { he: "ובסוף ניפגש ונשוב להיות", en: "And in the end we will all meet, and, once more, be–" },
      { he: "ילד ואבא ואמא", en: "A child, and a father, and a mother." },
      { he: "", en: "" },
      { he: "בכל פעם שיש יום הולדת", en: "Every time there is a birthday," },
      { he: "ולבית באים חברים", en: "And friends come over to our home," },
      { he: "אתה שם בכל אלה, משגיח למעלה", en: "You are there in all these moments, watching from above," },
      { he: "שרק יהיה פה טעים", en: "That it will all be delicious." },
      { he: "", en: "" },
      { he: "וכשבכי תינוק מפציע", en: "And when the cry of a baby erupts," },
      { he: "זה דוקר ושורף את הלב", en: "It pierces and burns the heart," },
      { he: "אתה שם בכל אלה, שומר מלמעלה", en: "You are there in all these moments, protecting from above," },
      { he: "שלא יהיה לי כואב", en: "That I won't be in pain." },
      { he: "", en: "" },
      { he: "ובינינו נמצא הים", en: "And between us there is an entire ocean;" },
      { he: "השמיים ואולי העולם", en: "the sky, and maybe the whole world." },
      { he: "וגם הם לא יפרידו בינינו, ילדי הקטן", en: "And they, too, won't separate us, my little child." },
      { he: "ואפשר לנסות ולחייך, לאהוב וללכת קדימה", en: "And we can try to smile, to love and to continue on forward," },
      { he: "ובסוף ניפגש ונשוב להיות", en: "And in the end we will all meet, and, once more, be–" },
      { he: "ילד, אבא ואמא.", en: "A child, father, and a mother." }
    ]
  },
  {
    id: 9,
    title: "Good Night, Sean",
    titleHebrew: "לילה טוב, שון",
    artist: "Hanan Ben Ari",
    videoUrl: "MXdmcsnsL_A",
    credits: "Written and composed by Hanan Ben-Ari, adapted from the farewell letters of Sgt. Sean Mondschein. Translated by Naama Ben-Dor.",
    context: "Sergeant Sean Mondschein, a soldier in the Golani Brigade, was born on December 30th, 1994, to Menachem and Ninet Mondschein. In June 2014, the Israel Defense Forces launched Operation Protective Edge after Hamas terrorists kidnapped and murdered three Israeli teenagers. On July 20, 2014, Sean was called to Gaza for an operation in the Shuja'iya neighborhood where he, along with six of his crew members, were killed when their APC was hit by an enemy missile. A few days before entering Gaza, he wrote farewell letters to his family and friends on his phone, in case he wouldn't return from battle. In 2018, the Israeli artist Hanan Ben-Ari adapted these letters to write and compose \"Good Night, Sean,\" as part of the \"Creation of My Life\" memorial project.",
    lyrics: [
      { he: "אמא", en: "Mom" },
      { he: "אני אוהב אותך באמת!", en: "I love you—truly!" },
      { he: "היית האמא הכי מדהימה בעולם", en: "You were the most amazing mom in the world" },
      { he: "יותר ממה שאפשר לבקש", en: "Better than anything one could asked for" },
      { he: "לא רציתי להדאיג אותך", en: "I didn't want to worry you" },
      { he: "מהכניסה לעזה או משהו", en: "About our entry into Gaza, or anything" },
      { he: "בבקשה תהיי חזקה בשבילי", en: "Please be strong for me" },
      { he: "ואם יקרה לי משהו תחייכי בגאווה", en: "And if anything happens to me, smile with pride" },
      { he: "אני אוהב אותך", en: "I love you" },
      { he: "אוהב אותך", en: "love you" },
      { he: "אוהב אותך", en: "love you" },
      { he: "", en: "" },
      { he: "אבא", en: "Dad" },
      { he: "היית אבא נפלא באמת!", en: "You were a wonderful dad–truly!" },
      { he: "אבא גבר גבר", en: "A 'man's-man' kind of dad." },
      { he: "למרות שרבנו בחודש האחרון", en: "Even though we've been fighting this past month…" },
      { he: "אל תייחס לזה משמעות", en: "Don't give it any thought." },
      { he: "אני אוהב אותך", en: "I love you" },
      { he: "אוהב אותך", en: "love you" },
      { he: "אוהב אותך", en: "love you" },
      { he: "אהבת אמת", en: "True love" },
      { he: "", en: "" },
      { he: "שחף, שירלי", en: "Shachaf, Shirley" },
      { he: "ולכל הקרובים והחברים", en: "And all of the relatives and friends," },
      { he: "אני אוהב אתכם!", en: "I love you!" },
      { he: "אני אתגעגע אליכם", en: "I will miss you" },
      { he: "ומקווה שלא תתגעגעו אליי", en: "And I hope that you won't miss me—" },
      { he: "כי אני שמח", en: "Because I'm happy" },
      { he: "שנפלה בחלקי הזכות", en: "to have had the privilege" },
      { he: "ליפול למען המדינה שלי", en: "To fall in the service of my country" },
      { he: "אני אוהב אותה", en: "I love her" },
      { he: "אוהב אותה", en: "Love her" },
      { he: "אוהב אותה", en: "Love her" },
      { he: "", en: "" },
      { he: "אז אם אתם קוראים את המכתבים", en: "So if you're reading these letters" },
      { he: "כנראה שהלכתי לישון...", en: "It looks like I've gone to sleep..." },
      { he: "לילה טוב", en: "Good night" },
      { he: "שון.", en: "Sean." }
    ]
  },
  {
    id: 10,
    title: "Fathers and Sons",
    titleHebrew: "אבות ובנים",
    artist: "Eviatar Banai",
    videoUrl: "3xEbBuAYbl8",
    credits: "Written and composed by Eviatar Banai (1997). Translated by Naama Ben-Dor.",
    context: "A powerful reflection on the cyclical nature of loss in Israeli society, where fathers bury sons and sons bury fathers. The song captures the universal pain of loss while speaking specifically to the Israeli experience of ongoing conflict.",
    lyrics: [
      { he: "תיכף אני ארצה שתלכו מפה,", en: "In a moment I'll want you all to leave," },
      { he: "שאוכל כבר ליפול בשקט.", en: "So that, finally, I can fall in silence." },
      { he: "שלא תראו את הפצעים נפערים—", en: "So you won't see the gaping wounds—" },
      { he: "שנשאר לבד ונשבר לאט,", en: "So we can stay alone, and break apart slowly." },
      { he: "", en: "" },
      { he: "תוותרו כבר ותלכו מפה,", en: "Give up already and leave this place," },
      { he: "שאוכל כבר לצעוק בשקט.", en: "So that, finally, I can scream in silence." },
      { he: "בלי המבט הקרוע שלכם—", en: "Without your piercing gaze—" },
      { he: "שנשאר לבד, ונשבר לאט.", en: "So we can stay alone, and break apart slowly." },
      { he: "", en: "" },
      { he: "אבות ובנים סבתות ונכדים,", en: "Fathers and sons, grandmothers and grandchildren," },
      { he: "הלב של אמא מתפוצץ;", en: "Mother's heart is exploding;" },
      { he: "מי אשם לה מי אשם לי?", en: "Who is to blame for her? Who is to blame for me?" },
      { he: "מי יפרד ממי?", en: "Who will part from whom?" },
      { he: "אבא בוכה על בן בוכה על אבא.", en: "A father weeps for a son—weeps for a father." },
      { he: "", en: "" },
      { he: "תיכף אני ארצה שתלכו מפה.", en: "In a moment I'll want you all to leave this place ." },
      { he: "לא אפחד ליפול; לא אפחד לגדול.", en: "I won't be scared to fall; I won't be scared to grow." },
      { he: "לטבוע או לשוט—", en: "To sink or to swim—" },
      { he: " לחיות או למות.", en: "To live or to die." },
      { he: "", en: "" },
      { he: "אבות ובנים, סבתות ונכדים,", en: "Fathers and sons, grandmothers and grandchildren," },
      { he: "הלב של אמא מתפוצץ;", en: "Mother's heart is exploding;" },
      { he: "מי אשם לה? מי אשם לי?", en: "Who is to blame for her? Who is to blame for me?" },
      { he: "מי יקבור את מי?", en: "Who will bury whom?" },
      { he: "אבא בוכה על בן, בוכה על אבא.", en: "A father weeps for a son; weeps for a father." },
      { he: "אבא בוכה על בן, בוכה על אבא.", en: "A father weeps for a son; weeps for a father." }
    ]
  },
  {
    id: 11,
    title: "Song With No Name",
    titleHebrew: "שיר ללא שם",
    artist: "Yehudit Ravitz",
    videoUrl: "TZbI4874BAg",
    credits: "Written and composed by Shalom Chanoch. Performed by Yehudit Ravitz in 1980.",
    context: "A deeply personal song about longing, connection, and the power of music to bridge distances. The song speaks to the universal experience of yearning for someone distant, while maintaining hope for reunion.",
    lyrics: [
      { he: "כי שירי הוא בת קול ברוח", en: "For my song is an echo in the wind," },
      { he: "מכתבי השלוח", en: "My sent letter," },
      { he: "מסילת חיי", en: "The railway of my life," },
      { he: "געגועי", en: "My longings," },
      { he: "הד תפילותי.", en: "The reverberation of my prayers." },
      { he: "", en: "" },
      { he: "כי שירי הוא עלה ברוח", en: "For my song is a leaf in the wind," },
      { he: "הנידף, השכוח", en: "Scattered, forgotten," },
      { he: "הוא האור הרך הנפקח", en: "It is the soft light that peeks" },
      { he: "בלילותי", en: "Into my nights," },
      { he: "הוא אתה ההולך אלי.", en: "It is you, coming to me." },
      { he: "", en: "" },
      { he: "בנדודי חולפות עלי", en: "In my wanderings, passing me by," },
      { he: "תמונות ונשמות", en: "Are pictures and souls," },
      { he: "ושמות שמות", en: "And names, names;" },
      { he: "אתה בא והולך אלי.", en: "You are on your way, coming toward me." },
      { he: "", en: "" },
      { he: "איי", en: "Oh," },
      { he: "עלטה סביב", en: "Darkness surrounds." },
      { he: "הלוואי שאתה מקשיב", en: "I hope you are listening," },
      { he: "אולי, אולי, אולי", en: "Maybe, maybe, maybe—" },
      { he: "אתה בא והולך אלי.", en: "You are on your way, and coming to me." },
      { he: "", en: "" },
      { he: "בדרכי הולכים איתי", en: "On my way, going with me," },
      { he: "נופים וניגונים", en: "Are landscapes, and melodies," },
      { he: "ופנים, פנים", en: "And faces, faces;" },
      { he: "אתה בא והולך אלי.", en: "You are on your way, and coming to me." },
      { he: "", en: "" },
      { he: "יה", en: "Oh," },
      { he: "דומיה סביב", en: "Silence surrounds." },
      { he: "והיה אם אתה מקשיב", en: "And if only you were listening," },
      { he: "אולי, אולי, אולי", en: "Maybe, maybe, maybe," },
      { he: "אתה בא והולך אלי", en: "You'd come and go to me." },
      { he: "אולי, אולי, אולי", en: "Maybe, maybe, maybe," },
      { he: "אתה בא והולך אלי.", en: "You'd come and go to me." },
      { he: "", en: "" },
      { he: "כי שירי הוא משב הרוח", en: "For my song is a gust of wind," },
      { he: "חלוני הפתוח", en: "My open window," },
      { he: "מעין כוחי, צחוק ובכי", en: "The wellspring of my power," },
      { he: "Laughter and tears,", en: "Laughter and tears," },
      { he: "קץ ייסורי", en: "The end of my suffering." },
      { he: "אתה בא והולך אלי.", en: "You are on your way, coming toward me." }
    ]
  },
  {
    id: 12,
    title: "Cyclamen Between the Rocks",
    titleHebrew: "רקפות בין הסלעים",
    artist: "Ariel Horowitz",
    videoUrl: "Svu0QOSz73c",
    credits: "Written and composed by Ariel Horowitz. Translated by Naama Ben-Dor.",
    context: "This song beautifully captures the resilience of the Israeli spirit - like cyclamen flowers that bloom between rocks, the beautiful faces of the nation emerge when needed most, especially in times of crisis and war.",
    lyrics: [
      { he: "בין הצפירות בכביש לרחובות המלוכלכים", en: "Between the sirens on the highway to the dirty streets" },
      { he: "בין משפחות הפשע לטלוויזיה השטחית", en: "Between the crime families and the shallow television" },
      { he: "כמו רקפות בין הסלעים", en: "Like cyclamen between the rocks" },
      { he: "הפנים היפים של הארץ מתחבאים", en: "The beautiful faces of the country are hiding" },
      { he: "", en: "" },
      { he: "בין הישנים ברחוב לדקירות במועדון", en: "Between the homeless in the street to the stabbings in the club" },
      { he: "בין מה שבדרך כלל קוראים בעיתון", en: "Between what you usually read in the newspaper" },
      { he: "כמו רקפות בין הסלעים", en: "Like cyclamen between the rocks" },
      { he: "הפנים היפים של הארץ מתחבאים", en: "The beautiful faces of the country are hiding" },
      { he: "", en: "" },
      { he: "וכשהיא לפתע צריכה", en: "And when she suddenly needs" },
      { he: "שמישהו יישכב בבוץ בתוך שוכה", en: "Someone to lie down in the mud in a trench" },
      { he: "לא תאמין איך הם מופיעים", en: "You won't believe how they appear" },
      { he: "כמו רקפות בין הסלעים", en: "Like cyclamen between the rocks" },
      { he: "", en: "" },
      { he: "בין הדגלים הכתומים לחולצה הכחולה", en: "Between the orange flags and the blue shirt" },
      { he: "בין שוק הפשפשים לקריית הממשלה", en: "Between the flea market and the government quarter" },
      { he: "כמו רקפות בין הסלעים", en: "Like cyclamen between the rocks" },
      { he: "הפנים היפים של הארץ מתחבאים", en: "The beautiful faces of the country are hiding" },
      { he: "", en: "" },
      { he: "וכשהיא לפתע צריכה", en: "And when she suddenly needs" },
      { he: "שמישהו יישכב בבוץ בתוך שוכה", en: "Someone to lie down in the mud in a trench" },
      { he: "לא תאמין איך הם מופיעים", en: "You won't believe how they appear" },
      { he: "כמו רקפות בין הסלעים", en: "Like cyclamen between the rocks" },
      { he: "", en: "" },
      { he: "בין מגדלי הפאר למרכז הקליטה", en: "Between the luxury towers and the absorption center" },
      { he: "בין פועלים זרים בשדות החיטה", en: "Between foreign workers in the wheat fields" },
      { he: "כמו רקפות בין הסלעים", en: "Like cyclamen between the rocks" },
      { he: "הפנים היפים של הארץ מתחבאים", en: "The beautiful faces of the country are hiding" },
      { he: "", en: "" },
      { he: "וכשהיא לפתע צריכה", en: "And when she suddenly needs" },
      { he: "שמישהו יישכב בבוץ בתוך שוכה", en: "Someone to lie down in the mud in a trench" },
      { he: "לא תאמין איך הם מופיעים", en: "You won't believe how they appear" }
    ]
  },
  {
    id: 13,
    title: "Nothing Will Hurt Me",
    titleHebrew: "שום דבר לא יפגע בי",
    artist: "Knesiyat HaSechel",
    videoUrl: "WN6JM5meZfU",
    credits: "Written and performed by Knesiyat HaSechel. Translated by Naama Ben-Dor.",
    context: "A haunting song about a soldier's promise to his family that nothing will hurt him - not a bullet, not danger. The tragic irony of the song lies in the final lines, where if the family is hearing these words, it means the promise could not be kept.",
    lyrics: [
      { he: "שום דבר לא יפגע בי, שום דבר", en: "Nothing will hurt me, nothing" },
      { he: "לא אישה לא כדור מחבלים, שום דבר", en: "Not a woman, not a bullet from terrorists, nothing" },
      { he: "כי ככה נשבעתי לאחי, אחותי, להורים", en: "Because that's what I swore to my brother, my sister, my parents" },
      { he: "ובכיתי בלילות ודאגתי בימים", en: "And I cried at night and worried during the day" },
      { he: "כי פחדתי שמשהו יפגע בהורים", en: "Because I was afraid that something would hurt my parents" },
      { he: "וקולו של אבי מהדהד לי בראש כבר שנים", en: "And my father's voice has been echoing in my head for years" },
      { he: "", en: "" },
      { he: "אם יקרה לך משהו", en: "If something happens to you" },
      { he: "אין לי טעם לחיים", en: "I have no reason to live" },
      { he: "אין לי טעם למחר", en: "I have no reason for tomorrow" },
      { he: "אין לי טעם לחיים", en: "I have no reason to live" },
      { he: "אין לי טעם למחר", en: "I have no reason for tomorrow" },
      { he: "", en: "" },
      { he: "אם אתם עומדים כאן מעלי", en: "If you are standing here above me" },
      { he: "כנראה שלא עמדתי בהבטחתי", en: "It seems I didn't keep my promise" },
      { he: "מצטער, בחיי", en: "I'm sorry, I swear" },
      { he: "מצטער, בחיי", en: "I'm sorry, I swear" },
      { he: "מצטער, בחיי", en: "I'm sorry, I swear" },
      { he: "", en: "" },
      { he: "אם יקרה לך משהו...", en: "If something happens to you..." },
      { he: "", en: "" },
      { he: "שום דבר לא יפגע בי", en: "Nothing will hurt me" },
      { he: "שום דבר", en: "Nothing" },
      { he: "לא אישה לא כדור מחבלים", en: "Not a woman, not a bullet from terrorists" },
      { he: "שום דבר", en: "Nothing" }
    ]
  }
];

// Make songs available globally for the React app
window.songs = songs;

// Export for potential module usage
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { songs };
}